/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  GetHotMoviesParams,
  GetLatestMoviesParams,
  GetMovieCatalogParams,
  GetMoviesByGenreParams,
  GetMoviesByYearParams,
  GetSimilarMoviesByMovieParams,
  MovieSearchDTO,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 支持关键词、类型、评分、年份等多条件组合搜索，返回分页结果。用于复杂搜索场景。
 * @summary 高级搜索（分页）
 */
export const searchMovies = (
  movieSearchDTO: MaybeRef<MovieSearchDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieSearchDTO = unref(movieSearchDTO);

  return customInstance<unknown>(
    {
      url: `/movies/search`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: movieSearchDTO,
      signal,
    },
    options,
  );
};

export const getSearchMoviesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchMovies>>,
    TError,
    { data: BodyType<MovieSearchDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchMovies>>,
  TError,
  { data: BodyType<MovieSearchDTO> },
  TContext
> => {
  const mutationKey = ["searchMovies"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchMovies>>,
    { data: BodyType<MovieSearchDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return searchMovies(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchMoviesMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchMovies>>
>;
export type SearchMoviesMutationBody = BodyType<MovieSearchDTO>;
export type SearchMoviesMutationError = ErrorType<unknown>;

/**
 * @summary 高级搜索（分页）
 */
export const useSearchMovies = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof searchMovies>>,
      TError,
      { data: BodyType<MovieSearchDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof searchMovies>>,
  TError,
  { data: BodyType<MovieSearchDTO> },
  TContext
> => {
  return useMutation(getSearchMoviesMutationOptions(options), queryClient);
};
/**
 * 用于浏览页面的简单目录筛选，支持类型、地区、评分、年代等维度的多选筛选。与POST /search分离，使用GET请求更符合RESTful规范。
 * @summary 电影目录筛选（GET，分页）
 */
export const getMovieCatalog = (
  params: MaybeRef<GetMovieCatalogParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/movies`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMovieCatalogQueryKey = (
  params?: MaybeRef<GetMovieCatalogParams>,
) => {
  return ["movies", ...(params ? [params] : [])] as const;
};

export const getGetMovieCatalogQueryOptions = <
  TData = Awaited<ReturnType<typeof getMovieCatalog>>,
  TError = ErrorType<unknown>,
>(
  params: MaybeRef<GetMovieCatalogParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieCatalog>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMovieCatalogQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMovieCatalog>>> = ({
    signal,
  }) => getMovieCatalog(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMovieCatalog>>,
    TError,
    TData
  >;
};

export type GetMovieCatalogQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMovieCatalog>>
>;
export type GetMovieCatalogQueryError = ErrorType<unknown>;

/**
 * @summary 电影目录筛选（GET，分页）
 */

export function useGetMovieCatalog<
  TData = Awaited<ReturnType<typeof getMovieCatalog>>,
  TError = ErrorType<unknown>,
>(
  params: MaybeRef<GetMovieCatalogParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieCatalog>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMovieCatalogQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 读取离线相似度结果，支持按相似类型筛选。
 * @summary 获取相似电影
 */
export const getSimilarMoviesByMovie = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesByMovieParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/similar`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetSimilarMoviesByMovieQueryKey = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesByMovieParams>,
) => {
  return ["movies", movieId, "similar", ...(params ? [params] : [])] as const;
};

export const getGetSimilarMoviesByMovieQueryOptions = <
  TData = Awaited<ReturnType<typeof getSimilarMoviesByMovie>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesByMovieParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimilarMoviesByMovie>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetSimilarMoviesByMovieQueryKey(movieId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSimilarMoviesByMovie>>
  > = ({ signal }) =>
    getSimilarMoviesByMovie(movieId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSimilarMoviesByMovie>>,
    TError,
    TData
  >;
};

export type GetSimilarMoviesByMovieQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSimilarMoviesByMovie>>
>;
export type GetSimilarMoviesByMovieQueryError = ErrorType<unknown>;

/**
 * @summary 获取相似电影
 */

export function useGetSimilarMoviesByMovie<
  TData = Awaited<ReturnType<typeof getSimilarMoviesByMovie>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesByMovieParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimilarMoviesByMovie>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSimilarMoviesByMovieQueryOptions(
    movieId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 根据电影ID获取详细信息，包括评分、类型、简介等完整数据。该接口为纯读取接口，不包含写副作用。
 * @summary 获取电影详情
 */
export const getMovieDetail = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/movies/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetMovieDetailQueryKey = (id: MaybeRef<number>) => {
  return ["movies", id] as const;
};

export const getGetMovieDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getMovieDetail>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMovieDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMovieDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMovieDetail>>> = ({
    signal,
  }) => getMovieDetail(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMovieDetail>>,
    TError,
    TData
  >;
};

export type GetMovieDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMovieDetail>>
>;
export type GetMovieDetailQueryError = ErrorType<unknown>;

/**
 * @summary 获取电影详情
 */

export function useGetMovieDetail<
  TData = Awaited<ReturnType<typeof getMovieDetail>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMovieDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMovieDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 返回数据库中存在的所有上映年份，按倒序排列
 * @summary 获取所有上映年份列表
 */
export const getAllYears = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/movies/years`, method: "GET", signal },
    options,
  );
};

export const getGetAllYearsQueryKey = () => {
  return ["movies", "years"] as const;
};

export const getGetAllYearsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllYears>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllYears>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllYearsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllYears>>> = ({
    signal,
  }) => getAllYears(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllYears>>,
    TError,
    TData
  >;
};

export type GetAllYearsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllYears>>
>;
export type GetAllYearsQueryError = ErrorType<unknown>;

/**
 * @summary 获取所有上映年份列表
 */

export function useGetAllYears<
  TData = Awaited<ReturnType<typeof getAllYears>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllYears>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllYearsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 根据上映年份筛选电影，支持分页
 * @summary 按年份筛选电影（分页）
 */
export const getMoviesByYear = (
  year: MaybeRef<number>,
  params?: MaybeRef<GetMoviesByYearParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  year = unref(year);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/movies/years/${year}`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetMoviesByYearQueryKey = (
  year: MaybeRef<number>,
  params?: MaybeRef<GetMoviesByYearParams>,
) => {
  return ["movies", "years", year, ...(params ? [params] : [])] as const;
};

export const getGetMoviesByYearQueryOptions = <
  TData = Awaited<ReturnType<typeof getMoviesByYear>>,
  TError = ErrorType<unknown>,
>(
  year: MaybeRef<number>,
  params?: MaybeRef<GetMoviesByYearParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoviesByYear>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMoviesByYearQueryKey(year, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesByYear>>> = ({
    signal,
  }) => getMoviesByYear(year, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(year)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMoviesByYear>>,
    TError,
    TData
  >;
};

export type GetMoviesByYearQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMoviesByYear>>
>;
export type GetMoviesByYearQueryError = ErrorType<unknown>;

/**
 * @summary 按年份筛选电影（分页）
 */

export function useGetMoviesByYear<
  TData = Awaited<ReturnType<typeof getMoviesByYear>>,
  TError = ErrorType<unknown>,
>(
  year: MaybeRef<number>,
  params?: MaybeRef<GetMoviesByYearParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoviesByYear>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMoviesByYearQueryOptions(year, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 返回数据库中存在的所有制片地区，用于前端分类展示
 * @summary 获取所有地区列表
 */
export const getAllRegions = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/movies/regions`, method: "GET", signal },
    options,
  );
};

export const getGetAllRegionsQueryKey = () => {
  return ["movies", "regions"] as const;
};

export const getGetAllRegionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllRegions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllRegions>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllRegionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRegions>>> = ({
    signal,
  }) => getAllRegions(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllRegions>>,
    TError,
    TData
  >;
};

export type GetAllRegionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllRegions>>
>;
export type GetAllRegionsQueryError = ErrorType<unknown>;

/**
 * @summary 获取所有地区列表
 */

export function useGetAllRegions<
  TData = Awaited<ReturnType<typeof getAllRegions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllRegions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllRegionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 按上映时间倒序排列，获取最新上映的电影
 * @summary 获取最新电影（分页）
 */
export const getLatestMovies = (
  params?: MaybeRef<GetLatestMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/movies/latest`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetLatestMoviesQueryKey = (
  params?: MaybeRef<GetLatestMoviesParams>,
) => {
  return ["movies", "latest", ...(params ? [params] : [])] as const;
};

export const getGetLatestMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getLatestMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetLatestMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetLatestMoviesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatestMovies>>> = ({
    signal,
  }) => getLatestMovies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLatestMovies>>,
    TError,
    TData
  >;
};

export type GetLatestMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLatestMovies>>
>;
export type GetLatestMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 获取最新电影（分页）
 */

export function useGetLatestMovies<
  TData = Awaited<ReturnType<typeof getLatestMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetLatestMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLatestMoviesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 直接读取离线分析结果表（stats_hot_movies）中的日榜结果
 * @summary 获取热门电影
 */
export const getHotMovies = (
  params?: MaybeRef<GetHotMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/movies/hot`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetHotMoviesQueryKey = (
  params?: MaybeRef<GetHotMoviesParams>,
) => {
  return ["movies", "hot", ...(params ? [params] : [])] as const;
};

export const getGetHotMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getHotMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetHotMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHotMovies>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetHotMoviesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHotMovies>>> = ({
    signal,
  }) => getHotMovies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHotMovies>>,
    TError,
    TData
  >;
};

export type GetHotMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHotMovies>>
>;
export type GetHotMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 获取热门电影
 */

export function useGetHotMovies<
  TData = Awaited<ReturnType<typeof getHotMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetHotMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHotMovies>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHotMoviesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 返回数据库中存在的所有电影类型，用于前端分类展示
 * @summary 获取所有电影类型列表
 */
export const getAllGenres = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/movies/genres`, method: "GET", signal },
    options,
  );
};

export const getGetAllGenresQueryKey = () => {
  return ["movies", "genres"] as const;
};

export const getGetAllGenresQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllGenres>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllGenres>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllGenresQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllGenres>>> = ({
    signal,
  }) => getAllGenres(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllGenres>>,
    TError,
    TData
  >;
};

export type GetAllGenresQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllGenres>>
>;
export type GetAllGenresQueryError = ErrorType<unknown>;

/**
 * @summary 获取所有电影类型列表
 */

export function useGetAllGenres<
  TData = Awaited<ReturnType<typeof getAllGenres>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllGenres>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllGenresQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 根据电影类型（如动作、喜剧、爱情等）筛选电影，支持分页
 * @summary 按类型筛选电影（分页）
 */
export const getMoviesByGenre = (
  genre: MaybeRef<string>,
  params?: MaybeRef<GetMoviesByGenreParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  genre = unref(genre);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/movies/genres/${genre}`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetMoviesByGenreQueryKey = (
  genre: MaybeRef<string>,
  params?: MaybeRef<GetMoviesByGenreParams>,
) => {
  return ["movies", "genres", genre, ...(params ? [params] : [])] as const;
};

export const getGetMoviesByGenreQueryOptions = <
  TData = Awaited<ReturnType<typeof getMoviesByGenre>>,
  TError = ErrorType<unknown>,
>(
  genre: MaybeRef<string>,
  params?: MaybeRef<GetMoviesByGenreParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoviesByGenre>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMoviesByGenreQueryKey(genre, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMoviesByGenre>>
  > = ({ signal }) => getMoviesByGenre(genre, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(genre)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMoviesByGenre>>,
    TError,
    TData
  >;
};

export type GetMoviesByGenreQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMoviesByGenre>>
>;
export type GetMoviesByGenreQueryError = ErrorType<unknown>;

/**
 * @summary 按类型筛选电影（分页）
 */

export function useGetMoviesByGenre<
  TData = Awaited<ReturnType<typeof getMoviesByGenre>>,
  TError = ErrorType<unknown>,
>(
  genre: MaybeRef<string>,
  params?: MaybeRef<GetMoviesByGenreParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoviesByGenre>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMoviesByGenreQueryOptions(genre, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 返回评分、年份等分段筛选的配置，方便前端渲染筛选菜单
 * @summary 获取筛选分段元数据
 */
export const getFilterMetadata = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/movies/filters/metadata`, method: "GET", signal },
    options,
  );
};

export const getGetFilterMetadataQueryKey = () => {
  return ["movies", "filters", "metadata"] as const;
};

export const getGetFilterMetadataQueryOptions = <
  TData = Awaited<ReturnType<typeof getFilterMetadata>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFilterMetadata>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetFilterMetadataQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFilterMetadata>>
  > = ({ signal }) => getFilterMetadata(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFilterMetadata>>,
    TError,
    TData
  >;
};

export type GetFilterMetadataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFilterMetadata>>
>;
export type GetFilterMetadataQueryError = ErrorType<unknown>;

/**
 * @summary 获取筛选分段元数据
 */

export function useGetFilterMetadata<
  TData = Awaited<ReturnType<typeof getFilterMetadata>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFilterMetadata>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFilterMetadataQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
