/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type { FavoriteFolderDTO } from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 根据ID获取收藏夹的详细信息
 * @summary 获取收藏夹详情
 */
export const getFavoriteFolderById = (
  folderId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  folderId = unref(folderId);

  return customInstance<unknown>(
    { url: `/favorite-folders/${folderId}`, method: "GET", signal },
    options,
  );
};

export const getGetFavoriteFolderByIdQueryKey = (
  folderId: MaybeRef<number>,
) => {
  return ["favorite-folders", folderId] as const;
};

export const getGetFavoriteFolderByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getFavoriteFolderById>>,
  TError = ErrorType<unknown>,
>(
  folderId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFavoriteFolderById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetFavoriteFolderByIdQueryKey(folderId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFavoriteFolderById>>
  > = ({ signal }) => getFavoriteFolderById(folderId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(folderId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFavoriteFolderById>>,
    TError,
    TData
  >;
};

export type GetFavoriteFolderByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFavoriteFolderById>>
>;
export type GetFavoriteFolderByIdQueryError = ErrorType<unknown>;

/**
 * @summary 获取收藏夹详情
 */

export function useGetFavoriteFolderById<
  TData = Awaited<ReturnType<typeof getFavoriteFolderById>>,
  TError = ErrorType<unknown>,
>(
  folderId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFavoriteFolderById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFavoriteFolderByIdQueryOptions(folderId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 修改收藏夹的名称、描述或公开状态
 * @summary 更新收藏夹
 */
export const updateFavoriteFolder = (
  folderId: MaybeRef<number>,
  favoriteFolderDTO: MaybeRef<FavoriteFolderDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  folderId = unref(folderId);
  favoriteFolderDTO = unref(favoriteFolderDTO);

  return customInstance<unknown>(
    {
      url: `/favorite-folders/${folderId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: favoriteFolderDTO,
      signal,
    },
    options,
  );
};

export const getUpdateFavoriteFolderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateFavoriteFolder>>,
    TError,
    { folderId: number; data: BodyType<FavoriteFolderDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateFavoriteFolder>>,
  TError,
  { folderId: number; data: BodyType<FavoriteFolderDTO> },
  TContext
> => {
  const mutationKey = ["updateFavoriteFolder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateFavoriteFolder>>,
    { folderId: number; data: BodyType<FavoriteFolderDTO> }
  > = (props) => {
    const { folderId, data } = props ?? {};

    return updateFavoriteFolder(folderId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateFavoriteFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateFavoriteFolder>>
>;
export type UpdateFavoriteFolderMutationBody = BodyType<FavoriteFolderDTO>;
export type UpdateFavoriteFolderMutationError = ErrorType<unknown>;

/**
 * @summary 更新收藏夹
 */
export const useUpdateFavoriteFolder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateFavoriteFolder>>,
      TError,
      { folderId: number; data: BodyType<FavoriteFolderDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateFavoriteFolder>>,
  TError,
  { folderId: number; data: BodyType<FavoriteFolderDTO> },
  TContext
> => {
  return useMutation(
    getUpdateFavoriteFolderMutationOptions(options),
    queryClient,
  );
};
/**
 * 删除收藏夹及其下的所有收藏记录
 * @summary 删除收藏夹
 */
export const deleteFavoriteFolder = (
  folderId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  folderId = unref(folderId);

  return customInstance<unknown>(
    { url: `/favorite-folders/${folderId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteFavoriteFolderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFavoriteFolder>>,
    TError,
    { folderId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteFavoriteFolder>>,
  TError,
  { folderId: number },
  TContext
> => {
  const mutationKey = ["deleteFavoriteFolder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteFavoriteFolder>>,
    { folderId: number }
  > = (props) => {
    const { folderId } = props ?? {};

    return deleteFavoriteFolder(folderId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteFavoriteFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFavoriteFolder>>
>;

export type DeleteFavoriteFolderMutationError = ErrorType<unknown>;

/**
 * @summary 删除收藏夹
 */
export const useDeleteFavoriteFolder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteFavoriteFolder>>,
      TError,
      { folderId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteFavoriteFolder>>,
  TError,
  { folderId: number },
  TContext
> => {
  return useMutation(
    getDeleteFavoriteFolderMutationOptions(options),
    queryClient,
  );
};
/**
 * 获取当前用户的所有收藏夹
 * @summary 获取我的收藏夹列表
 */
export const getMyFavoriteFolders = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/favorite-folders`, method: "GET", signal },
    options,
  );
};

export const getGetMyFavoriteFoldersQueryKey = () => {
  return ["favorite-folders"] as const;
};

export const getGetMyFavoriteFoldersQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyFavoriteFolders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMyFavoriteFolders>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyFavoriteFoldersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyFavoriteFolders>>
  > = ({ signal }) => getMyFavoriteFolders(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyFavoriteFolders>>,
    TError,
    TData
  >;
};

export type GetMyFavoriteFoldersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyFavoriteFolders>>
>;
export type GetMyFavoriteFoldersQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的收藏夹列表
 */

export function useGetMyFavoriteFolders<
  TData = Awaited<ReturnType<typeof getMyFavoriteFolders>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyFavoriteFolders>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyFavoriteFoldersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 创建一个新的自定义收藏夹
 * @summary 创建收藏夹
 */
export const createFavoriteFolder = (
  favoriteFolderDTO: MaybeRef<FavoriteFolderDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  favoriteFolderDTO = unref(favoriteFolderDTO);

  return customInstance<unknown>(
    {
      url: `/favorite-folders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: favoriteFolderDTO,
      signal,
    },
    options,
  );
};

export const getCreateFavoriteFolderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFavoriteFolder>>,
    TError,
    { data: BodyType<FavoriteFolderDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFavoriteFolder>>,
  TError,
  { data: BodyType<FavoriteFolderDTO> },
  TContext
> => {
  const mutationKey = ["createFavoriteFolder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFavoriteFolder>>,
    { data: BodyType<FavoriteFolderDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return createFavoriteFolder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateFavoriteFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFavoriteFolder>>
>;
export type CreateFavoriteFolderMutationBody = BodyType<FavoriteFolderDTO>;
export type CreateFavoriteFolderMutationError = ErrorType<unknown>;

/**
 * @summary 创建收藏夹
 */
export const useCreateFavoriteFolder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createFavoriteFolder>>,
      TError,
      { data: BodyType<FavoriteFolderDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof createFavoriteFolder>>,
  TError,
  { data: BodyType<FavoriteFolderDTO> },
  TContext
> => {
  return useMutation(
    getCreateFavoriteFolderMutationOptions(options),
    queryClient,
  );
};
/**
 * 获取用户的收藏夹总数
 * @summary 统计收藏夹数量
 */
export const getFavoriteFolderCount = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/favorite-folders/count`, method: "GET", signal },
    options,
  );
};

export const getGetFavoriteFolderCountQueryKey = () => {
  return ["favorite-folders", "count"] as const;
};

export const getGetFavoriteFolderCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getFavoriteFolderCount>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFavoriteFolderCount>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetFavoriteFolderCountQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFavoriteFolderCount>>
  > = ({ signal }) => getFavoriteFolderCount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFavoriteFolderCount>>,
    TError,
    TData
  >;
};

export type GetFavoriteFolderCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFavoriteFolderCount>>
>;
export type GetFavoriteFolderCountQueryError = ErrorType<unknown>;

/**
 * @summary 统计收藏夹数量
 */

export function useGetFavoriteFolderCount<
  TData = Awaited<ReturnType<typeof getFavoriteFolderCount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFavoriteFolderCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFavoriteFolderCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
