/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type { UpdateAvatarParams, UpdateUserProfileDTO } from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 返回当前登录用户可编辑的资料信息，用于个人中心页面初始化
 * @summary 获取我的个人资料
 */
export const getMyProfile = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/users/me/profile`, method: "GET", signal },
    options,
  );
};

export const getGetMyProfileQueryKey = () => {
  return ["users", "me", "profile"] as const;
};

export const getGetMyProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyProfile>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProfile>>> = ({
    signal,
  }) => getMyProfile(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyProfile>>,
    TError,
    TData
  >;
};

export type GetMyProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyProfile>>
>;
export type GetMyProfileQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的个人资料
 */

export function useGetMyProfile<
  TData = Awaited<ReturnType<typeof getMyProfile>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 支持昵称、头像、主页、邮箱的增量更新，仅更新请求体中提供的字段
 * @summary 更新我的个人资料
 */
export const updateMyProfile = (
  updateUserProfileDTO: MaybeRef<UpdateUserProfileDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  updateUserProfileDTO = unref(updateUserProfileDTO);

  return customInstance<unknown>(
    {
      url: `/users/me/profile`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserProfileDTO,
      signal,
    },
    options,
  );
};

export const getUpdateMyProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyProfile>>,
    TError,
    { data: BodyType<UpdateUserProfileDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyProfile>>,
  TError,
  { data: BodyType<UpdateUserProfileDTO> },
  TContext
> => {
  const mutationKey = ["updateMyProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyProfile>>,
    { data: BodyType<UpdateUserProfileDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return updateMyProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyProfile>>
>;
export type UpdateMyProfileMutationBody = BodyType<UpdateUserProfileDTO>;
export type UpdateMyProfileMutationError = ErrorType<unknown>;

/**
 * @summary 更新我的个人资料
 */
export const useUpdateMyProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMyProfile>>,
      TError,
      { data: BodyType<UpdateUserProfileDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateMyProfile>>,
  TError,
  { data: BodyType<UpdateUserProfileDTO> },
  TContext
> => {
  return useMutation(getUpdateMyProfileMutationOptions(options), queryClient);
};
/**
 * 更新当前登录用户的头像 URL
 * @summary 更新用户头像
 */
export const updateAvatar = (
  params: MaybeRef<UpdateAvatarParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/users/me/avatar`, method: "PATCH", params: unref(params), signal },
    options,
  );
};

export const getUpdateAvatarMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAvatar>>,
    TError,
    { params: UpdateAvatarParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAvatar>>,
  TError,
  { params: UpdateAvatarParams },
  TContext
> => {
  const mutationKey = ["updateAvatar"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAvatar>>,
    { params: UpdateAvatarParams }
  > = (props) => {
    const { params } = props ?? {};

    return updateAvatar(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAvatarMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAvatar>>
>;

export type UpdateAvatarMutationError = ErrorType<unknown>;

/**
 * @summary 更新用户头像
 */
export const useUpdateAvatar = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAvatar>>,
      TError,
      { params: UpdateAvatarParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateAvatar>>,
  TError,
  { params: UpdateAvatarParams },
  TContext
> => {
  return useMutation(getUpdateAvatarMutationOptions(options), queryClient);
};
/**
 * 根据用户ID获取公开的用户信息（不包含敏感信息如邮箱、角色等）
 * @summary 获取公开用户信息
 */
export const getPublicUserInfo = (
  userId: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  userId = unref(userId);

  return customInstance<unknown>(
    { url: `/users/${userId}`, method: "GET", signal },
    options,
  );
};

export const getGetPublicUserInfoQueryKey = (userId: MaybeRef<string>) => {
  return ["users", userId] as const;
};

export const getGetPublicUserInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getPublicUserInfo>>,
  TError = ErrorType<unknown>,
>(
  userId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPublicUserInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPublicUserInfoQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPublicUserInfo>>
  > = ({ signal }) => getPublicUserInfo(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(userId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPublicUserInfo>>,
    TError,
    TData
  >;
};

export type GetPublicUserInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPublicUserInfo>>
>;
export type GetPublicUserInfoQueryError = ErrorType<unknown>;

/**
 * @summary 获取公开用户信息
 */

export function useGetPublicUserInfo<
  TData = Awaited<ReturnType<typeof getPublicUserInfo>>,
  TError = ErrorType<unknown>,
>(
  userId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPublicUserInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPublicUserInfoQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 根据请求头中的 Token 获取当前登录用户的详细信息
 * @summary 获取当前用户信息
 */
export const getCurrentUserInfo = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/users/me`, method: "GET", signal },
    options,
  );
};

export const getGetCurrentUserInfoQueryKey = () => {
  return ["users", "me"] as const;
};

export const getGetCurrentUserInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserInfo>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCurrentUserInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserInfo>>
  > = ({ signal }) => getCurrentUserInfo(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserInfo>>,
    TError,
    TData
  >;
};

export type GetCurrentUserInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserInfo>>
>;
export type GetCurrentUserInfoQueryError = ErrorType<unknown>;

/**
 * @summary 获取当前用户信息
 */

export function useGetCurrentUserInfo<
  TData = Awaited<ReturnType<typeof getCurrentUserInfo>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
