/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type { GetPersonListParams } from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 支持按中英文名模糊搜索，分页返回
 * @summary 搜索影人列表
 */
export const getPersonList = (
  params?: MaybeRef<GetPersonListParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/people`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetPersonListQueryKey = (
  params?: MaybeRef<GetPersonListParams>,
) => {
  return ["people", ...(params ? [params] : [])] as const;
};

export const getGetPersonListQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPersonListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonList>>> = ({
    signal,
  }) => getPersonList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonList>>,
    TError,
    TData
  >;
};

export type GetPersonListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonList>>
>;
export type GetPersonListQueryError = ErrorType<unknown>;

/**
 * @summary 搜索影人列表
 */

export function useGetPersonList<
  TData = Awaited<ReturnType<typeof getPersonList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 包含生平简介、出生地、职业等详细信息
 * @summary 获取影人详情
 */
export const getPersonDetail = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/people/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetPersonDetailQueryKey = (id: MaybeRef<number>) => {
  return ["people", id] as const;
};

export const getGetPersonDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonDetail>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPersonDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonDetail>>> = ({
    signal,
  }) => getPersonDetail(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonDetail>>,
    TError,
    TData
  >;
};

export type GetPersonDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonDetail>>
>;
export type GetPersonDetailQueryError = ErrorType<unknown>;

/**
 * @summary 获取影人详情
 */

export function useGetPersonDetail<
  TData = Awaited<ReturnType<typeof getPersonDetail>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 查找该影人参与（导演或出演）的所有电影
 * @summary 获取影人相关电影
 */
export const getPersonMovies = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/people/${id}/movies`, method: "GET", signal },
    options,
  );
};

export const getGetPersonMoviesQueryKey = (id: MaybeRef<number>) => {
  return ["people", id, "movies"] as const;
};

export const getGetPersonMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonMovies>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPersonMoviesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonMovies>>> = ({
    signal,
  }) => getPersonMovies(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonMovies>>,
    TError,
    TData
  >;
};

export type GetPersonMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonMovies>>
>;
export type GetPersonMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 获取影人相关电影
 */

export function useGetPersonMovies<
  TData = Awaited<ReturnType<typeof getPersonMovies>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonMoviesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
