/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

export type AddFavoriteParams = {
  /**
   * 收藏夹ID，不传则加入默认收藏夹
   * @minimum 1
   */
  folderId?: number;
};
