/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 电影ID列表
 */
export interface BatchIdsDTO {
  /**
   * ID列表
   * @minItems 1
   */
  ids: number[];
}
