/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 电影目录筛选请求参数（GET请求）
 */
export interface CatalogQueryDTO {
  /**
   * 页码 (从1开始)
   * @minimum 1
   */
  page?: number;
  /**
   * 每页显示数量
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** 电影类型筛选（支持多选，逗号分隔） */
  genres?: string;
  /** 地区筛选（支持多选，逗号分隔） */
  regions?: string;
  /**
   * 最低评分筛选 (1.0-10.0)
   * @minimum 1
   * @maximum 10
   */
  minScore?: number;
  /**
   * 最高评分筛选 (1.0-10.0)
   * @minimum 1
   * @maximum 10
   */
  maxScore?: number;
  /** 起始年份范围筛选 */
  startYear?: number;
  /** 结束年份范围筛选 */
  endYear?: number;
  /**
   * 排序字段: score(评分), year(年份), votes(热度)
   * @pattern ^(score|year|votes)$
   */
  sortBy?: string;
  /**
   * 排序方向: desc(降序), asc(升序)
   * @pattern ^(desc|asc)$
   */
  sortOrder?: string;
  genresList?: string[];
  regionsList?: string[];
}
