/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 修改密码请求参数
 */
export interface ChangePasswordDTO {
  /**
   * 旧密码
   * @minLength 1
   */
  oldPassword: string;
  /**
   * 新密码
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword: string;
}
