/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import type { ColdGemVOActorsItem } from "./coldGemVOActorsItem";
import type { ColdGemVODirectorsItem } from "./coldGemVODirectorsItem";
import type { ColdGemVOWritersItem } from "./coldGemVOWritersItem";

/**
 * 冷门佳作信息
 */
export interface ColdGemVO {
  /** 电影ID */
  id?: number;
  /** 电影名称 */
  name?: string;
  /** 电影别名 */
  alias?: string;
  /** 演员列表 (包含name和role等信息) */
  actors?: ColdGemVOActorsItem[];
  /** 封面图片路径 (自动拼接域名) */
  cover?: string;
  /** 导演列表 */
  directors?: ColdGemVODirectorsItem[];
  /** 本站评分 (1-10) */
  score?: number;
  /** 豆瓣评分 (1-10) */
  doubanScore?: number;
  /** 本站评分人数 */
  votes?: number;
  /** 豆瓣评分人数 */
  doubanVotes?: number;
  /** 电影类型 (逗号分隔) */
  genres?: string;
  /** IMDB ID */
  imdbId?: string;
  /** 语言 */
  languages?: string;
  /** 片长 */
  mins?: string;
  /** 制片国家/地区 */
  regions?: string;
  /** 上映日期 */
  releaseDate?: string;
  /** 剧情简介 */
  storyline?: string;
  /** 上映年份 */
  year?: number;
  /** 编剧列表 */
  writers?: ColdGemVOWritersItem[];
  /** 上榜理由(如: 9.0分但在本站仅100人看过) */
  reason?: string;
}
