/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 评论展示对象 (包含用户信息和点赞状态)
 */
export interface CommentVO {
  /** 评论ID */
  id?: number;
  /** 评论者ID */
  userId?: string;
  /** 电影ID */
  movieId?: number;
  /** 评论标题 */
  title?: string;
  /** 评论类型 (1:短评, 2:长评) */
  type?: number;
  /** 评论内容 */
  content?: string;
  /** 获赞数 */
  votes?: number;
  /** 评论发布时间 */
  commentTime?: string;
  /** 乐观锁版本号 */
  version?: number;
  /** 评论者昵称 */
  userNickname?: string;
  /** 评论者头像URL */
  userAvatar?: string;
  /** 该用户对电影的评分 (1-5，可能为空) */
  rating?: number;
  /** 当前登录用户是否已点赞该评论 */
  isLiked?: boolean;
  /** 评论内容纯文本摘要（长评时有效） */
  contentSummary?: string;
  /** 评论内容纯文本长度（长评时有效） */
  contentLength?: number;
  /** 是否为 JSON 格式内容（长评时有效） */
  isJsonContent?: boolean;
}
