/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 收藏夹详情视图对象
 */
export interface FavoriteFolderVO {
  /** 收藏夹ID */
  id?: number;
  /** 收藏夹名称 */
  name?: string;
  /** 收藏夹描述 */
  description?: string;
  /** 是否公开：0-私密, 1-公开 */
  isPublic?: number;
  /** 电影数量 */
  movieCount?: number;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
}
