/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 创建/更新收藏夹请求参数
 */
export interface FavoriteFolderDTO {
  /** 收藏夹ID（更新时需要） */
  id?: number;
  /**
   * 收藏夹名称
   * @minLength 0
   * @maxLength 100
   */
  name: string;
  /**
   * 收藏夹描述
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  /** 是否公开：0-私密, 1-公开 */
  isPublic?: number;
}
