/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import type { CatalogQueryDTO } from "./catalogQueryDTO";

export type GetMovieCatalogParams = {
  catalogQuery: CatalogQueryDTO;
};
