/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

export type GetSimilarMoviesParams = {
  /**
   * 相似类型：1-内容相似，2-协同过滤
   */
  type?: number;
  /**
   * 返回数量，默认10条，最多100条
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
