/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import type { GetTrendingMoviesPeriod } from "./getTrendingMoviesPeriod";

export type GetTrendingMoviesParams = {
  /**
   * 周期类型: DAILY, WEEKLY, MONTHLY，默认为 DAILY
   */
  period?: GetTrendingMoviesPeriod;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
