/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 用户登录请求参数
 */
export interface LoginDTO {
  /**
   * 用户账号
   * @minLength 1
   */
  id: string;
  /**
   * 用户密码
   * @minLength 1
   */
  password: string;
}
