/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 电影高级搜索请求参数
 */
export interface MovieSearchDTO {
  /**
   * 页码 (从1开始)
   * @minimum 1
   */
  page?: number;
  /**
   * 每页显示数量
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /**
   * 搜索关键词（匹配电影名、别名或简介）
   * @minLength 0
   * @maxLength 100
   */
  keyword?: string;
  /** 电影类型筛选（支持多选） */
  genres?: string[];
  /**
   * 最低评分筛选 (1.0-10.0)
   * @minimum 1
   * @maximum 10
   */
  minScore?: number;
  /**
   * 最高评分筛选 (1.0-10.0)
   * @minimum 1
   * @maximum 10
   */
  maxScore?: number;
  /**
   * 特定年份精确筛选
   * @pattern ^(19|20)\d{2}$
   */
  year?: string;
  /** 起始年份范围筛选 */
  startYear?: number;
  /** 结束年份范围筛选 */
  endYear?: number;
  /** 地区筛选（支持多选） */
  regions?: string[];
  /** 导演筛选（支持多选，匹配导演名称） */
  directors?: string[];
  /** 演员筛选（支持多选，匹配演员名称） */
  actors?: string[];
  /**
   * 排序字段: score(评分), year(年份), votes(热度)
   * @pattern ^(score|year|votes)$
   */
  sortBy?: string;
  /**
   * 排序方向: desc(降序), asc(升序)
   * @pattern ^(desc|asc)$
   */
  sortOrder?: string;
}
