/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import type { MovieItemVOActorsItem } from "./movieItemVOActorsItem";
import type { MovieItemVODirectorsItem } from "./movieItemVODirectorsItem";

/**
 * 我的电影条目 (包含电影信息和记录时间)
 */
export interface MovieItemVO {
  /** 电影ID */
  movieId?: number;
  /** 电影名称 */
  movieName?: string;
  /** 电影封面URL */
  cover?: string;
  /** 豆瓣评分 (1-10) */
  score?: number;
  /** 评分人数 */
  votes?: number;
  /** 电影类型 (逗号分隔) */
  genres?: string;
  /** 上映年份 */
  year?: number;
  /** 导演列表 */
  directors?: MovieItemVODirectorsItem[];
  /** 演员列表 */
  actors?: MovieItemVOActorsItem[];
  /** 制片国家/地区 */
  regions?: string;
  /** 片长 */
  mins?: string;
  /** 剧情简介 */
  storyline?: string;
  /** 记录时间 */
  favoriteTime?: string;
}
