/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 我的评分记录 (包含电影信息)
 */
export interface MyRatingVO {
  /** 评分记录ID（使用 movie_id） */
  id?: number;
  /** 电影ID */
  movieId?: number;
  /** 电影名称 */
  movieName?: string;
  /** 电影海报URL */
  posterUrl?: string;
  /** 我的评分 (1-5) */
  rating?: number;
  /** 评分时间 */
  ratingTime?: string;
  /** 电影简介 */
  description?: string;
}
