/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 影人 (演员/导演/编剧) 详细信息
 */
export interface Person {
  /** 影人ID */
  id?: number;
  /** 中文名 */
  name?: string;
  /** 性别 */
  sex?: string;
  /** 英文名 */
  nameEn?: string;
  /** 中文名 (备用字段) */
  nameZh?: string;
  /** 出生日期 */
  birth?: string;
  /** 出生地 */
  birthplace?: string;
  /** 职业 */
  profession?: string;
  /** 影人简介 */
  biography?: string;
  /** 影人照片 URL */
  avatar?: string;
}
