/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 公开用户信息（不包含敏感信息）
 */
export interface PublicUserVO {
  /** 用户ID */
  id?: string;
  /** 用户昵称 */
  nickname?: string;
  /** 用户头像URL */
  avatar?: string;
  /** 用户豆瓣主页链接 */
  url?: string;
  /** 用户获得的赞数 */
  receivedLikes?: number;
  /** 用户发布的影评数 */
  commentCount?: number;
}
