/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 用户评分实体
 */
export interface Rating {
  /** 用户ID */
  userId?: string;
  /** 电影ID */
  movieId?: number;
  /** 评分值 (1-5 星) */
  rating?: number;
  /** 评分时间 */
  ratingTime?: string;
}
