/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 记录浏览历史请求参数
 */
export interface RecordViewHistoryDTO {
  /**
   * 电影ID
   * @minimum 1
   */
  movieId: number;
}
