/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

export type RefreshPersonalizedRecommendationsAllAdminParams = {
  /**
   * 确认清除全部用户缓存，必须传 true
   */
  confirmAll?: boolean;
};
