/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 用户注册请求参数
 */
export interface RegisterDTO {
  /**
   * 用户账号 (唯一标识)
   * @minLength 4
   * @maxLength 20
   */
  id: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 2147483647
   */
  password: string;
  /**
   * 用户昵称
   * @minLength 1
   */
  nickname: string;
  /** 电子邮箱 */
  email?: string;
  /** 个人主页/豆瓣主页链接 */
  url?: string;
}
