/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

export type RemoveFavoriteParams = {
  /**
   * 收藏夹ID，指定则只从该收藏夹移除
   * @minimum 1
   */
  folderId?: number;
};
