/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * Tiptap 富文本内容信息
 */
export interface TiptapContentDTO {
  /** 原始 JSON 内容 */
  jsonContent?: string;
  /** 纯文本内容（去除格式） */
  plainText?: string;
  /** 内容摘要（前200字） */
  summary?: string;
  /** 纯文本长度 */
  textLength?: number;
  /** 是否包含图片 */
  hasImages?: boolean;
  /** 图片数量 */
  imageCount?: number;
}
