/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 趋势榜单返回项
 */
export interface TrendingMovieDTO {
  /** 电影ID */
  movieId?: number;
  /** 电影名称 */
  name?: string;
  /** 封面图片路径 */
  cover?: string;
  /** 豆瓣评分 */
  doubanScore?: number;
  /** 上映年份 */
  year?: number;
  /** 制片国家/地区 */
  regions?: string;
  /** 电影类型(逗号分隔) */
  genres?: string;
  /** 热度分值 */
  hotScore?: number;
  /** 计算日期(yyyy-MM-dd) */
  calcDate?: string;
  /** 统计周期 */
  period?: string;
  /** 排名，从1开始 */
  rank?: number;
}
