/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 更新评论及评分请求参数
 */
export interface UpdateCommentWithRatingDTO {
  /**
   * 评论内容
   * @minLength 0
   * @maxLength 500
   */
  content: string;
  /**
   * 评分(1-5)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
}
