/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 更新长评请求参数
 */
export interface UpdateLongReviewDTO {
  /**
   * 长评标题
   * @minLength 0
   * @maxLength 100
   */
  title: string;
  /**
   * 长评内容（Tiptap JSON 格式）
   * @minLength 1
   */
  content: string;
}
