/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 更新评论内容请求参数
 */
export interface UpdateCommentContentDTO {
  /**
   * 评论内容
   * @minLength 0
   * @maxLength 500
   */
  content: string;
}
