/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

export type UpdateAvatarParams = {
  /**
   * 头像图片的访问 URL
   * @minLength 0
   * @maxLength 500
   */
  avatarUrl: string;
};
