/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 更新用户个人资料请求参数（支持增量更新）
 */
export interface UpdateUserProfileDTO {
  /**
   * 用户昵称
   * @minLength 0
   * @maxLength 50
   */
  nickname?: string;
  /**
   * 用户头像URL
   * @minLength 0
   * @maxLength 500
   */
  avatar?: string;
  /**
   * 个人主页链接
   * @minLength 0
   * @maxLength 500
   */
  url?: string;
  /**
   * 电子邮箱
   * @minLength 0
   * @maxLength 100
   */
  email?: string;
}
