/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 用户实体
 */
export interface User {
  /** 用户ID (唯一账号) */
  id?: string;
  /** 用户昵称 */
  nickname?: string;
  /** 用户头像 URL */
  avatar?: string;
  /** 个人主页/豆瓣链接 */
  url?: string;
  /** 电子邮箱 */
  email?: string;
  /** 用户角色 (0:管理员, 1:普通用户) */
  role?: number;
  /** 账号状态 (0:正常, 1:被禁用/冻结) */
  status?: number;
  /** 密码版本号，用于失效旧 Token（修改密码后递增） */
  passwordVersion?: number;
  /** 账号创建时间 */
  createTime?: string;
  /** 最后更新时间 */
  updateTime?: string;
}
