/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 登录成功后返回的用户信息
 */
export interface UserVO {
  /** 用户ID */
  id?: string;
  /** 用户昵称 */
  nickname?: string;
  /** 用户头像URL (自动拼接域名) */
  avatar?: string;
  /** 个人主页链接 */
  url?: string;
  /** 电子邮箱 */
  email?: string;
  /** 用户角色 (0:管理员, 1:普通用户) */
  role?: number;
  /** JWT 访问令牌 (短效) */
  accessToken?: string;
  /** 用户获得的赞数 */
  receivedLikes?: number;
  /** 用户发布的影评数 */
  commentCount?: number;
  /** 用户看过的电影数量 */
  watchedCount?: number;
}
