/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */

/**
 * 用户个人资料信息
 */
export interface UserProfileVO {
  /** 用户ID */
  id?: string;
  /** 用户昵称 */
  nickname?: string;
  /** 用户头像URL (自动拼接域名) */
  avatar?: string;
  /** 个人主页链接 */
  url?: string;
  /** 电子邮箱 */
  email?: string;
}
