/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  AddFavoriteParams,
  BatchIdsDTO,
  GetFolderMoviesParams,
  GetMyFavoritesParams,
  RemoveFavoriteParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 查询当前用户是否收藏了某部电影
 * @summary 查询收藏状态
 */
export const isFavorited = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/favorites/movies/${movieId}`, method: "GET", signal },
    options,
  );
};

export const getIsFavoritedQueryKey = (movieId: MaybeRef<number>) => {
  return ["favorites", "movies", movieId] as const;
};

export const getIsFavoritedQueryOptions = <
  TData = Awaited<ReturnType<typeof isFavorited>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isFavorited>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getIsFavoritedQueryKey(movieId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof isFavorited>>> = ({
    signal,
  }) => isFavorited(movieId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof isFavorited>>, TError, TData>;
};

export type IsFavoritedQueryResult = NonNullable<
  Awaited<ReturnType<typeof isFavorited>>
>;
export type IsFavoritedQueryError = ErrorType<unknown>;

/**
 * @summary 查询收藏状态
 */

export function useIsFavorited<
  TData = Awaited<ReturnType<typeof isFavorited>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isFavorited>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getIsFavoritedQueryOptions(movieId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 将电影加入用户的收藏夹
 * @summary 添加收藏
 */
export const addFavorite = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<AddFavoriteParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/favorites/movies/${movieId}`,
      method: "POST",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getAddFavoriteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFavorite>>,
    TError,
    { movieId: number; params?: AddFavoriteParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { movieId: number; params?: AddFavoriteParams },
  TContext
> => {
  const mutationKey = ["addFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addFavorite>>,
    { movieId: number; params?: AddFavoriteParams }
  > = (props) => {
    const { movieId, params } = props ?? {};

    return addFavorite(movieId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof addFavorite>>
>;

export type AddFavoriteMutationError = ErrorType<unknown>;

/**
 * @summary 添加收藏
 */
export const useAddFavorite = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addFavorite>>,
      TError,
      { movieId: number; params?: AddFavoriteParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { movieId: number; params?: AddFavoriteParams },
  TContext
> => {
  return useMutation(getAddFavoriteMutationOptions(options), queryClient);
};
/**
 * 将电影从用户的收藏夹移除
 * @summary 取消收藏
 */
export const removeFavorite = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<RemoveFavoriteParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/favorites/movies/${movieId}`,
      method: "DELETE",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getRemoveFavoriteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorite>>,
    TError,
    { movieId: number; params?: RemoveFavoriteParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { movieId: number; params?: RemoveFavoriteParams },
  TContext
> => {
  const mutationKey = ["removeFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFavorite>>,
    { movieId: number; params?: RemoveFavoriteParams }
  > = (props) => {
    const { movieId, params } = props ?? {};

    return removeFavorite(movieId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFavorite>>
>;

export type RemoveFavoriteMutationError = ErrorType<unknown>;

/**
 * @summary 取消收藏
 */
export const useRemoveFavorite = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeFavorite>>,
      TError,
      { movieId: number; params?: RemoveFavoriteParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { movieId: number; params?: RemoveFavoriteParams },
  TContext
> => {
  return useMutation(getRemoveFavoriteMutationOptions(options), queryClient);
};
/**
 * 批量移除收藏夹中的多部电影
 * @summary 批量删除收藏
 */
export const deleteFavoritesBatch = (
  batchIdsDTO: MaybeRef<BatchIdsDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  batchIdsDTO = unref(batchIdsDTO);

  return customInstance<unknown>(
    {
      url: `/favorites/batch-delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchIdsDTO,
      signal,
    },
    options,
  );
};

export const getDeleteFavoritesBatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFavoritesBatch>>,
    TError,
    { data: BodyType<BatchIdsDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteFavoritesBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  const mutationKey = ["deleteFavoritesBatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteFavoritesBatch>>,
    { data: BodyType<BatchIdsDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return deleteFavoritesBatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteFavoritesBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFavoritesBatch>>
>;
export type DeleteFavoritesBatchMutationBody = BodyType<BatchIdsDTO>;
export type DeleteFavoritesBatchMutationError = ErrorType<unknown>;

/**
 * @summary 批量删除收藏
 */
export const useDeleteFavoritesBatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteFavoritesBatch>>,
      TError,
      { data: BodyType<BatchIdsDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteFavoritesBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  return useMutation(
    getDeleteFavoritesBatchMutationOptions(options),
    queryClient,
  );
};
/**
 * 分页获取当前用户收藏的所有电影，包含收藏时间
 * @summary 获取我的收藏列表
 */
export const getMyFavorites = (
  params?: MaybeRef<GetMyFavoritesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/favorites`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMyFavoritesQueryKey = (
  params?: MaybeRef<GetMyFavoritesParams>,
) => {
  return ["favorites", ...(params ? [params] : [])] as const;
};

export const getGetMyFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyFavorites>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyFavoritesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyFavoritesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyFavorites>>> = ({
    signal,
  }) => getMyFavorites(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyFavorites>>,
    TError,
    TData
  >;
};

export type GetMyFavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyFavorites>>
>;
export type GetMyFavoritesQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的收藏列表
 */

export function useGetMyFavorites<
  TData = Awaited<ReturnType<typeof getMyFavorites>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyFavoritesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyFavoritesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 清空当前用户的所有收藏
 * @summary 清空收藏夹
 */
export const clearMyFavorites = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/favorites`, method: "DELETE", signal },
    options,
  );
};

export const getClearMyFavoritesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clearMyFavorites>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clearMyFavorites>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["clearMyFavorites"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clearMyFavorites>>,
    void
  > = () => {
    return clearMyFavorites(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearMyFavoritesMutationResult = NonNullable<
  Awaited<ReturnType<typeof clearMyFavorites>>
>;

export type ClearMyFavoritesMutationError = ErrorType<unknown>;

/**
 * @summary 清空收藏夹
 */
export const useClearMyFavorites = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clearMyFavorites>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof clearMyFavorites>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getClearMyFavoritesMutationOptions(options), queryClient);
};
/**
 * 分页获取指定收藏夹内的电影列表
 * @summary 获取收藏夹内电影
 */
export const getFolderMovies = (
  folderId: MaybeRef<number>,
  params?: MaybeRef<GetFolderMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  folderId = unref(folderId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/favorites/folders/${folderId}`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetFolderMoviesQueryKey = (
  folderId: MaybeRef<number>,
  params?: MaybeRef<GetFolderMoviesParams>,
) => {
  return [
    "favorites",
    "folders",
    folderId,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetFolderMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getFolderMovies>>,
  TError = ErrorType<unknown>,
>(
  folderId: MaybeRef<number>,
  params?: MaybeRef<GetFolderMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFolderMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetFolderMoviesQueryKey(folderId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolderMovies>>> = ({
    signal,
  }) => getFolderMovies(folderId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(folderId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFolderMovies>>,
    TError,
    TData
  >;
};

export type GetFolderMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFolderMovies>>
>;
export type GetFolderMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 获取收藏夹内电影
 */

export function useGetFolderMovies<
  TData = Awaited<ReturnType<typeof getFolderMovies>>,
  TError = ErrorType<unknown>,
>(
  folderId: MaybeRef<number>,
  params?: MaybeRef<GetFolderMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFolderMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFolderMoviesQueryOptions(
    folderId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 统计当前用户的收藏电影总数
 * @summary 获取收藏总数
 */
export const getFavoritesCount = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/favorites/count`, method: "GET", signal },
    options,
  );
};

export const getGetFavoritesCountQueryKey = () => {
  return ["favorites", "count"] as const;
};

export const getGetFavoritesCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getFavoritesCount>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFavoritesCount>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetFavoritesCountQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFavoritesCount>>
  > = ({ signal }) => getFavoritesCount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFavoritesCount>>,
    TError,
    TData
  >;
};

export type GetFavoritesCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFavoritesCount>>
>;
export type GetFavoritesCountQueryError = ErrorType<unknown>;

/**
 * @summary 获取收藏总数
 */

export function useGetFavoritesCount<
  TData = Awaited<ReturnType<typeof getFavoritesCount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFavoritesCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFavoritesCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
