/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  AdminMovieDTO,
  AdminPersonDTO,
  Genre,
  GetCommentListAdminParams,
  GetMovieListAdminParams,
  GetPersonListAdminParams,
  GetUserListAdminParams,
  RefreshPersonalizedRecommendationsAllAdminParams,
  Region,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 修改电影地区信息，自动清除缓存
 * @summary 更新地区
 */
export const updateRegionAdmin = (
  id: MaybeRef<number>,
  region: MaybeRef<Region>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  region = unref(region);

  return customInstance<unknown>(
    {
      url: `/admin/regions/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: region,
      signal,
    },
    options,
  );
};

export const getUpdateRegionAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRegionAdmin>>,
    TError,
    { id: number; data: BodyType<Region> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRegionAdmin>>,
  TError,
  { id: number; data: BodyType<Region> },
  TContext
> => {
  const mutationKey = ["updateRegionAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRegionAdmin>>,
    { id: number; data: BodyType<Region> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateRegionAdmin(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRegionAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRegionAdmin>>
>;
export type UpdateRegionAdminMutationBody = BodyType<Region>;
export type UpdateRegionAdminMutationError = ErrorType<unknown>;

/**
 * @summary 更新地区
 */
export const useUpdateRegionAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRegionAdmin>>,
      TError,
      { id: number; data: BodyType<Region> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateRegionAdmin>>,
  TError,
  { id: number; data: BodyType<Region> },
  TContext
> => {
  return useMutation(getUpdateRegionAdminMutationOptions(options), queryClient);
};
/**
 * 删除电影地区，自动清除缓存
 * @summary 删除地区
 */
export const deleteRegionAdmin = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/regions/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteRegionAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRegionAdmin>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRegionAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteRegionAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRegionAdmin>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteRegionAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRegionAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRegionAdmin>>
>;

export type DeleteRegionAdminMutationError = ErrorType<unknown>;

/**
 * @summary 删除地区
 */
export const useDeleteRegionAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRegionAdmin>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteRegionAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteRegionAdminMutationOptions(options), queryClient);
};
/**
 * 修改影人资料
 * @summary 更新影人信息
 */
export const updatePersonAdmin = (
  id: MaybeRef<number>,
  adminPersonDTO: MaybeRef<AdminPersonDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  adminPersonDTO = unref(adminPersonDTO);

  return customInstance<unknown>(
    {
      url: `/admin/people/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminPersonDTO,
      signal,
    },
    options,
  );
};

export const getUpdatePersonAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePersonAdmin>>,
    TError,
    { id: number; data: BodyType<AdminPersonDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePersonAdmin>>,
  TError,
  { id: number; data: BodyType<AdminPersonDTO> },
  TContext
> => {
  const mutationKey = ["updatePersonAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePersonAdmin>>,
    { id: number; data: BodyType<AdminPersonDTO> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updatePersonAdmin(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePersonAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePersonAdmin>>
>;
export type UpdatePersonAdminMutationBody = BodyType<AdminPersonDTO>;
export type UpdatePersonAdminMutationError = ErrorType<unknown>;

/**
 * @summary 更新影人信息
 */
export const useUpdatePersonAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePersonAdmin>>,
      TError,
      { id: number; data: BodyType<AdminPersonDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updatePersonAdmin>>,
  TError,
  { id: number; data: BodyType<AdminPersonDTO> },
  TContext
> => {
  return useMutation(getUpdatePersonAdminMutationOptions(options), queryClient);
};
/**
 * 删除影人记录
 * @summary 删除影人
 */
export const deletePersonAdmin = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/people/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeletePersonAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePersonAdmin>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePersonAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deletePersonAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePersonAdmin>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deletePersonAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePersonAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePersonAdmin>>
>;

export type DeletePersonAdminMutationError = ErrorType<unknown>;

/**
 * @summary 删除影人
 */
export const useDeletePersonAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePersonAdmin>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deletePersonAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeletePersonAdminMutationOptions(options), queryClient);
};
/**
 * 修改已存在的电影数据
 * @summary 更新电影信息
 */
export const updateMovieAdmin = (
  id: MaybeRef<number>,
  adminMovieDTO: MaybeRef<AdminMovieDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  adminMovieDTO = unref(adminMovieDTO);

  return customInstance<unknown>(
    {
      url: `/admin/movies/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: adminMovieDTO,
      signal,
    },
    options,
  );
};

export const getUpdateMovieAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMovieAdmin>>,
    TError,
    { id: number; data: BodyType<AdminMovieDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMovieAdmin>>,
  TError,
  { id: number; data: BodyType<AdminMovieDTO> },
  TContext
> => {
  const mutationKey = ["updateMovieAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMovieAdmin>>,
    { id: number; data: BodyType<AdminMovieDTO> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateMovieAdmin(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMovieAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMovieAdmin>>
>;
export type UpdateMovieAdminMutationBody = BodyType<AdminMovieDTO>;
export type UpdateMovieAdminMutationError = ErrorType<unknown>;

/**
 * @summary 更新电影信息
 */
export const useUpdateMovieAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMovieAdmin>>,
      TError,
      { id: number; data: BodyType<AdminMovieDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateMovieAdmin>>,
  TError,
  { id: number; data: BodyType<AdminMovieDTO> },
  TContext
> => {
  return useMutation(getUpdateMovieAdminMutationOptions(options), queryClient);
};
/**
 * 根据ID物理删除电影记录
 * @summary 删除电影
 */
export const deleteMovieAdmin = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/movies/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteMovieAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMovieAdmin>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMovieAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteMovieAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMovieAdmin>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteMovieAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMovieAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMovieAdmin>>
>;

export type DeleteMovieAdminMutationError = ErrorType<unknown>;

/**
 * @summary 删除电影
 */
export const useDeleteMovieAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMovieAdmin>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteMovieAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteMovieAdminMutationOptions(options), queryClient);
};
/**
 * 修改电影类型信息，自动清除缓存
 * @summary 更新类型
 */
export const updateGenreAdmin = (
  id: MaybeRef<number>,
  genre: MaybeRef<Genre>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  genre = unref(genre);

  return customInstance<unknown>(
    {
      url: `/admin/genres/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: genre,
      signal,
    },
    options,
  );
};

export const getUpdateGenreAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGenreAdmin>>,
    TError,
    { id: number; data: BodyType<Genre> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGenreAdmin>>,
  TError,
  { id: number; data: BodyType<Genre> },
  TContext
> => {
  const mutationKey = ["updateGenreAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGenreAdmin>>,
    { id: number; data: BodyType<Genre> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateGenreAdmin(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGenreAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGenreAdmin>>
>;
export type UpdateGenreAdminMutationBody = BodyType<Genre>;
export type UpdateGenreAdminMutationError = ErrorType<unknown>;

/**
 * @summary 更新类型
 */
export const useUpdateGenreAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateGenreAdmin>>,
      TError,
      { id: number; data: BodyType<Genre> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateGenreAdmin>>,
  TError,
  { id: number; data: BodyType<Genre> },
  TContext
> => {
  return useMutation(getUpdateGenreAdminMutationOptions(options), queryClient);
};
/**
 * 删除电影类型，自动清除缓存
 * @summary 删除类型
 */
export const deleteGenreAdmin = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/genres/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteGenreAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGenreAdmin>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGenreAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteGenreAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGenreAdmin>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteGenreAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGenreAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGenreAdmin>>
>;

export type DeleteGenreAdminMutationError = ErrorType<unknown>;

/**
 * @summary 删除类型
 */
export const useDeleteGenreAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteGenreAdmin>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteGenreAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteGenreAdminMutationOptions(options), queryClient);
};
/**
 * 返回所有电影地区的完整信息
 * @summary 获取所有地区（完整对象）
 */
export const getRegionListAdmin = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/admin/regions`, method: "GET", signal },
    options,
  );
};

export const getGetRegionListAdminQueryKey = () => {
  return ["admin", "regions"] as const;
};

export const getGetRegionListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getRegionListAdmin>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRegionListAdmin>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetRegionListAdminQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRegionListAdmin>>
  > = ({ signal }) => getRegionListAdmin(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRegionListAdmin>>,
    TError,
    TData
  >;
};

export type GetRegionListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRegionListAdmin>>
>;
export type GetRegionListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 获取所有地区（完整对象）
 */

export function useGetRegionListAdmin<
  TData = Awaited<ReturnType<typeof getRegionListAdmin>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRegionListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRegionListAdminQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 添加新的电影地区，自动清除缓存
 * @summary 新增地区
 */
export const addRegionAdmin = (
  region: MaybeRef<Region>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  region = unref(region);

  return customInstance<unknown>(
    {
      url: `/admin/regions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: region,
      signal,
    },
    options,
  );
};

export const getAddRegionAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addRegionAdmin>>,
    TError,
    { data: BodyType<Region> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addRegionAdmin>>,
  TError,
  { data: BodyType<Region> },
  TContext
> => {
  const mutationKey = ["addRegionAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addRegionAdmin>>,
    { data: BodyType<Region> }
  > = (props) => {
    const { data } = props ?? {};

    return addRegionAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddRegionAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof addRegionAdmin>>
>;
export type AddRegionAdminMutationBody = BodyType<Region>;
export type AddRegionAdminMutationError = ErrorType<unknown>;

/**
 * @summary 新增地区
 */
export const useAddRegionAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addRegionAdmin>>,
      TError,
      { data: BodyType<Region> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addRegionAdmin>>,
  TError,
  { data: BodyType<Region> },
  TContext
> => {
  return useMutation(getAddRegionAdminMutationOptions(options), queryClient);
};
/**
 * 分页查询所有演员/导演/编剧
 * @summary 影人列表管理
 */
export const getPersonListAdmin = (
  params?: MaybeRef<GetPersonListAdminParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/admin/people`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetPersonListAdminQueryKey = (
  params?: MaybeRef<GetPersonListAdminParams>,
) => {
  return ["admin", "people", ...(params ? [params] : [])] as const;
};

export const getGetPersonListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPersonListAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPersonListAdmin>>
  > = ({ signal }) => getPersonListAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonListAdmin>>,
    TError,
    TData
  >;
};

export type GetPersonListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonListAdmin>>
>;
export type GetPersonListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 影人列表管理
 */

export function useGetPersonListAdmin<
  TData = Awaited<ReturnType<typeof getPersonListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonListAdminQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 录入新的影人资料
 * @summary 新增影人
 */
export const addPersonAdmin = (
  adminPersonDTO: MaybeRef<AdminPersonDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  adminPersonDTO = unref(adminPersonDTO);

  return customInstance<unknown>(
    {
      url: `/admin/people`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminPersonDTO,
      signal,
    },
    options,
  );
};

export const getAddPersonAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPersonAdmin>>,
    TError,
    { data: BodyType<AdminPersonDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPersonAdmin>>,
  TError,
  { data: BodyType<AdminPersonDTO> },
  TContext
> => {
  const mutationKey = ["addPersonAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPersonAdmin>>,
    { data: BodyType<AdminPersonDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return addPersonAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPersonAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof addPersonAdmin>>
>;
export type AddPersonAdminMutationBody = BodyType<AdminPersonDTO>;
export type AddPersonAdminMutationError = ErrorType<unknown>;

/**
 * @summary 新增影人
 */
export const useAddPersonAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPersonAdmin>>,
      TError,
      { data: BodyType<AdminPersonDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addPersonAdmin>>,
  TError,
  { data: BodyType<AdminPersonDTO> },
  TContext
> => {
  return useMutation(getAddPersonAdminMutationOptions(options), queryClient);
};
/**
 * 后台查询电影列表 (无视上下架状态)
 * @summary 电影列表管理
 */
export const getMovieListAdmin = (
  params?: MaybeRef<GetMovieListAdminParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/admin/movies`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMovieListAdminQueryKey = (
  params?: MaybeRef<GetMovieListAdminParams>,
) => {
  return ["admin", "movies", ...(params ? [params] : [])] as const;
};

export const getGetMovieListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getMovieListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMovieListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMovieListAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMovieListAdmin>>
  > = ({ signal }) => getMovieListAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMovieListAdmin>>,
    TError,
    TData
  >;
};

export type GetMovieListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMovieListAdmin>>
>;
export type GetMovieListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 电影列表管理
 */

export function useGetMovieListAdmin<
  TData = Awaited<ReturnType<typeof getMovieListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMovieListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMovieListAdminQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 录入新的电影数据
 * @summary 新增电影
 */
export const addMovieAdmin = (
  adminMovieDTO: MaybeRef<AdminMovieDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  adminMovieDTO = unref(adminMovieDTO);

  return customInstance<unknown>(
    {
      url: `/admin/movies`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: adminMovieDTO,
      signal,
    },
    options,
  );
};

export const getAddMovieAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addMovieAdmin>>,
    TError,
    { data: BodyType<AdminMovieDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addMovieAdmin>>,
  TError,
  { data: BodyType<AdminMovieDTO> },
  TContext
> => {
  const mutationKey = ["addMovieAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMovieAdmin>>,
    { data: BodyType<AdminMovieDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return addMovieAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddMovieAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof addMovieAdmin>>
>;
export type AddMovieAdminMutationBody = BodyType<AdminMovieDTO>;
export type AddMovieAdminMutationError = ErrorType<unknown>;

/**
 * @summary 新增电影
 */
export const useAddMovieAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addMovieAdmin>>,
      TError,
      { data: BodyType<AdminMovieDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addMovieAdmin>>,
  TError,
  { data: BodyType<AdminMovieDTO> },
  TContext
> => {
  return useMutation(getAddMovieAdminMutationOptions(options), queryClient);
};
/**
 * 返回所有电影类型的完整信息
 * @summary 获取所有类型（完整对象）
 */
export const getGenreListAdmin = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/admin/genres`, method: "GET", signal },
    options,
  );
};

export const getGetGenreListAdminQueryKey = () => {
  return ["admin", "genres"] as const;
};

export const getGetGenreListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getGenreListAdmin>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getGenreListAdmin>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetGenreListAdminQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGenreListAdmin>>
  > = ({ signal }) => getGenreListAdmin(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGenreListAdmin>>,
    TError,
    TData
  >;
};

export type GetGenreListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGenreListAdmin>>
>;
export type GetGenreListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 获取所有类型（完整对象）
 */

export function useGetGenreListAdmin<
  TData = Awaited<ReturnType<typeof getGenreListAdmin>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGenreListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGenreListAdminQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 添加新的电影类型，自动清除缓存
 * @summary 新增类型
 */
export const addGenreAdmin = (
  genre: MaybeRef<Genre>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  genre = unref(genre);

  return customInstance<unknown>(
    {
      url: `/admin/genres`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: genre,
      signal,
    },
    options,
  );
};

export const getAddGenreAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addGenreAdmin>>,
    TError,
    { data: BodyType<Genre> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addGenreAdmin>>,
  TError,
  { data: BodyType<Genre> },
  TContext
> => {
  const mutationKey = ["addGenreAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addGenreAdmin>>,
    { data: BodyType<Genre> }
  > = (props) => {
    const { data } = props ?? {};

    return addGenreAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddGenreAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof addGenreAdmin>>
>;
export type AddGenreAdminMutationBody = BodyType<Genre>;
export type AddGenreAdminMutationError = ErrorType<unknown>;

/**
 * @summary 新增类型
 */
export const useAddGenreAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addGenreAdmin>>,
      TError,
      { data: BodyType<Genre> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addGenreAdmin>>,
  TError,
  { data: BodyType<Genre> },
  TContext
> => {
  return useMutation(getAddGenreAdminMutationOptions(options), queryClient);
};
/**
 * 分页查询所有注册用户
 * @summary 用户列表管理
 */
export const getUserListAdmin = (
  params?: MaybeRef<GetUserListAdminParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/admin/users`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetUserListAdminQueryKey = (
  params?: MaybeRef<GetUserListAdminParams>,
) => {
  return ["admin", "users", ...(params ? [params] : [])] as const;
};

export const getGetUserListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetUserListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetUserListAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserListAdmin>>
  > = ({ signal }) => getUserListAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserListAdmin>>,
    TError,
    TData
  >;
};

export type GetUserListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserListAdmin>>
>;
export type GetUserListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 用户列表管理
 */

export function useGetUserListAdmin<
  TData = Awaited<ReturnType<typeof getUserListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetUserListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserListAdminQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 返回系统总用户数、总电影数等统计指标
 * @summary 获取仪表盘统计数据
 */
export const getDashboardStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/admin/dashboard/stats`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardStatsQueryKey = () => {
  return ["admin", "dashboard", "stats"] as const;
};

export const getGetDashboardStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDashboardStats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetDashboardStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardStats>>
  > = ({ signal }) => getDashboardStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStats>>,
    TError,
    TData
  >;
};

export type GetDashboardStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardStats>>
>;
export type GetDashboardStatsQueryError = ErrorType<unknown>;

/**
 * @summary 获取仪表盘统计数据
 */

export function useGetDashboardStats<
  TData = Awaited<ReturnType<typeof getDashboardStats>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardStats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 查看所有用户发布的评论，用于内容审核
 * @summary 评论列表管理
 */
export const getCommentListAdmin = (
  params?: MaybeRef<GetCommentListAdminParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/admin/comments`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetCommentListAdminQueryKey = (
  params?: MaybeRef<GetCommentListAdminParams>,
) => {
  return ["admin", "comments", ...(params ? [params] : [])] as const;
};

export const getGetCommentListAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getCommentListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetCommentListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCommentListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCommentListAdminQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCommentListAdmin>>
  > = ({ signal }) => getCommentListAdmin(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCommentListAdmin>>,
    TError,
    TData
  >;
};

export type GetCommentListAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCommentListAdmin>>
>;
export type GetCommentListAdminQueryError = ErrorType<unknown>;

/**
 * @summary 评论列表管理
 */

export function useGetCommentListAdmin<
  TData = Awaited<ReturnType<typeof getCommentListAdmin>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetCommentListAdminParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCommentListAdmin>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCommentListAdminQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 根据ID注销用户账号
 * @summary 注销用户
 */
export const deleteUserAdmin = (
  id: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/users/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteUserAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserAdmin>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserAdmin>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteUserAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserAdmin>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserAdmin>>
>;

export type DeleteUserAdminMutationError = ErrorType<unknown>;

/**
 * @summary 注销用户
 */
export const useDeleteUserAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserAdmin>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteUserAdmin>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteUserAdminMutationOptions(options), queryClient);
};
/**
 * 清除指定用户的猜你喜欢缓存，下一次请求将回源刷新
 * @summary 刷新指定用户猜你喜欢缓存
 */
export const refreshPersonalizedRecommendationsByUserAdmin = (
  targetUserId: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  targetUserId = unref(targetUserId);

  return customInstance<unknown>(
    {
      url: `/admin/recommendations/personalized/cache/${targetUserId}`,
      method: "DELETE",
      signal,
    },
    options,
  );
};

export const getRefreshPersonalizedRecommendationsByUserAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>,
    TError,
    { targetUserId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>,
  TError,
  { targetUserId: string },
  TContext
> => {
  const mutationKey = ["refreshPersonalizedRecommendationsByUserAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>,
    { targetUserId: string }
  > = (props) => {
    const { targetUserId } = props ?? {};

    return refreshPersonalizedRecommendationsByUserAdmin(
      targetUserId,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshPersonalizedRecommendationsByUserAdminMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>
  >;

export type RefreshPersonalizedRecommendationsByUserAdminMutationError =
  ErrorType<unknown>;

/**
 * @summary 刷新指定用户猜你喜欢缓存
 */
export const useRefreshPersonalizedRecommendationsByUserAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>,
      TError,
      { targetUserId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof refreshPersonalizedRecommendationsByUserAdmin>>,
  TError,
  { targetUserId: string },
  TContext
> => {
  return useMutation(
    getRefreshPersonalizedRecommendationsByUserAdminMutationOptions(options),
    queryClient,
  );
};
/**
 * 清除全部用户的猜你喜欢缓存，需显式确认后执行
 * @summary 刷新全量猜你喜欢缓存
 */
export const refreshPersonalizedRecommendationsAllAdmin = (
  params?: MaybeRef<RefreshPersonalizedRecommendationsAllAdminParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/admin/recommendations/personalized/cache/all`,
      method: "DELETE",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getRefreshPersonalizedRecommendationsAllAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>,
    TError,
    { params?: RefreshPersonalizedRecommendationsAllAdminParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>,
  TError,
  { params?: RefreshPersonalizedRecommendationsAllAdminParams },
  TContext
> => {
  const mutationKey = ["refreshPersonalizedRecommendationsAllAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>,
    { params?: RefreshPersonalizedRecommendationsAllAdminParams }
  > = (props) => {
    const { params } = props ?? {};

    return refreshPersonalizedRecommendationsAllAdmin(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshPersonalizedRecommendationsAllAdminMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>
  >;

export type RefreshPersonalizedRecommendationsAllAdminMutationError =
  ErrorType<unknown>;

/**
 * @summary 刷新全量猜你喜欢缓存
 */
export const useRefreshPersonalizedRecommendationsAllAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>,
      TError,
      { params?: RefreshPersonalizedRecommendationsAllAdminParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof refreshPersonalizedRecommendationsAllAdmin>>,
  TError,
  { params?: RefreshPersonalizedRecommendationsAllAdminParams },
  TContext
> => {
  return useMutation(
    getRefreshPersonalizedRecommendationsAllAdminMutationOptions(options),
    queryClient,
  );
};
/**
 * 管理员强制删除违规评论
 * @summary 删除评论
 */
export const deleteCommentAdmin = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customInstance<unknown>(
    { url: `/admin/comments/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteCommentAdminMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCommentAdmin>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCommentAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCommentAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCommentAdmin>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCommentAdmin(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCommentAdmin>>
>;

export type DeleteCommentAdminMutationError = ErrorType<unknown>;

/**
 * @summary 删除评论
 */
export const useDeleteCommentAdmin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCommentAdmin>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteCommentAdmin>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDeleteCommentAdminMutationOptions(options),
    queryClient,
  );
};
