/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type { BatchIdsDTO, GetMyWatchedListParams } from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 查询当前用户是否看过某部电影
 * @summary 查询看过状态
 */
export const isWatched = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/watched-movies/${movieId}`, method: "GET", signal },
    options,
  );
};

export const getIsWatchedQueryKey = (movieId: MaybeRef<number>) => {
  return ["watched-movies", movieId] as const;
};

export const getIsWatchedQueryOptions = <
  TData = Awaited<ReturnType<typeof isWatched>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isWatched>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getIsWatchedQueryKey(movieId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof isWatched>>> = ({
    signal,
  }) => isWatched(movieId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof isWatched>>, TError, TData>;
};

export type IsWatchedQueryResult = NonNullable<
  Awaited<ReturnType<typeof isWatched>>
>;
export type IsWatchedQueryError = ErrorType<unknown>;

/**
 * @summary 查询看过状态
 */

export function useIsWatched<
  TData = Awaited<ReturnType<typeof isWatched>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof isWatched>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getIsWatchedQueryOptions(movieId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 将电影标记为当前用户已看过
 * @summary 标记看过
 */
export const addWatched = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/watched-movies/${movieId}`, method: "POST", signal },
    options,
  );
};

export const getAddWatchedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addWatched>>,
    TError,
    { movieId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addWatched>>,
  TError,
  { movieId: number },
  TContext
> => {
  const mutationKey = ["addWatched"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addWatched>>,
    { movieId: number }
  > = (props) => {
    const { movieId } = props ?? {};

    return addWatched(movieId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddWatchedMutationResult = NonNullable<
  Awaited<ReturnType<typeof addWatched>>
>;

export type AddWatchedMutationError = ErrorType<unknown>;

/**
 * @summary 标记看过
 */
export const useAddWatched = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addWatched>>,
      TError,
      { movieId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof addWatched>>,
  TError,
  { movieId: number },
  TContext
> => {
  return useMutation(getAddWatchedMutationOptions(options), queryClient);
};
/**
 * 取消当前用户对电影的看过标记
 * @summary 取消看过
 */
export const removeWatched = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/watched-movies/${movieId}`, method: "DELETE", signal },
    options,
  );
};

export const getRemoveWatchedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeWatched>>,
    TError,
    { movieId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeWatched>>,
  TError,
  { movieId: number },
  TContext
> => {
  const mutationKey = ["removeWatched"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeWatched>>,
    { movieId: number }
  > = (props) => {
    const { movieId } = props ?? {};

    return removeWatched(movieId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveWatchedMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeWatched>>
>;

export type RemoveWatchedMutationError = ErrorType<unknown>;

/**
 * @summary 取消看过
 */
export const useRemoveWatched = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeWatched>>,
      TError,
      { movieId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof removeWatched>>,
  TError,
  { movieId: number },
  TContext
> => {
  return useMutation(getRemoveWatchedMutationOptions(options), queryClient);
};
/**
 * 批量查询当前用户对多部电影的看过状态
 * @summary 批量查询看过状态
 */
export const getBatchWatchedStatus = (
  batchIdsDTO: MaybeRef<BatchIdsDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  batchIdsDTO = unref(batchIdsDTO);

  return customInstance<unknown>(
    {
      url: `/watched-movies/status/batch`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchIdsDTO,
      signal,
    },
    options,
  );
};

export const getGetBatchWatchedStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getBatchWatchedStatus>>,
    TError,
    { data: BodyType<BatchIdsDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getBatchWatchedStatus>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  const mutationKey = ["getBatchWatchedStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getBatchWatchedStatus>>,
    { data: BodyType<BatchIdsDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return getBatchWatchedStatus(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetBatchWatchedStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof getBatchWatchedStatus>>
>;
export type GetBatchWatchedStatusMutationBody = BodyType<BatchIdsDTO>;
export type GetBatchWatchedStatusMutationError = ErrorType<unknown>;

/**
 * @summary 批量查询看过状态
 */
export const useGetBatchWatchedStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getBatchWatchedStatus>>,
      TError,
      { data: BodyType<BatchIdsDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof getBatchWatchedStatus>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  return useMutation(
    getGetBatchWatchedStatusMutationOptions(options),
    queryClient,
  );
};
/**
 * 批量取消当前用户对多部电影的看过标记
 * @summary 批量取消看过
 */
export const deleteWatchedBatch = (
  batchIdsDTO: MaybeRef<BatchIdsDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  batchIdsDTO = unref(batchIdsDTO);

  return customInstance<unknown>(
    {
      url: `/watched-movies/batch-delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchIdsDTO,
      signal,
    },
    options,
  );
};

export const getDeleteWatchedBatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWatchedBatch>>,
    TError,
    { data: BodyType<BatchIdsDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWatchedBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  const mutationKey = ["deleteWatchedBatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWatchedBatch>>,
    { data: BodyType<BatchIdsDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return deleteWatchedBatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWatchedBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWatchedBatch>>
>;
export type DeleteWatchedBatchMutationBody = BodyType<BatchIdsDTO>;
export type DeleteWatchedBatchMutationError = ErrorType<unknown>;

/**
 * @summary 批量取消看过
 */
export const useDeleteWatchedBatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteWatchedBatch>>,
      TError,
      { data: BodyType<BatchIdsDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteWatchedBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  return useMutation(
    getDeleteWatchedBatchMutationOptions(options),
    queryClient,
  );
};
/**
 * 分页获取当前用户标记看过的电影列表
 * @summary 获取我的看过列表
 */
export const getMyWatchedList = (
  params?: MaybeRef<GetMyWatchedListParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/watched-movies`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMyWatchedListQueryKey = (
  params?: MaybeRef<GetMyWatchedListParams>,
) => {
  return ["watched-movies", ...(params ? [params] : [])] as const;
};

export const getGetMyWatchedListQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyWatchedList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyWatchedListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyWatchedList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyWatchedListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyWatchedList>>
  > = ({ signal }) => getMyWatchedList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyWatchedList>>,
    TError,
    TData
  >;
};

export type GetMyWatchedListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyWatchedList>>
>;
export type GetMyWatchedListQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的看过列表
 */

export function useGetMyWatchedList<
  TData = Awaited<ReturnType<typeof getMyWatchedList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyWatchedListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyWatchedList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyWatchedListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 清空当前用户所有看过标记
 * @summary 清空看过记录
 */
export const clearWatched = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/watched-movies`, method: "DELETE", signal },
    options,
  );
};

export const getClearWatchedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clearWatched>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clearWatched>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["clearWatched"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clearWatched>>,
    void
  > = () => {
    return clearWatched(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearWatchedMutationResult = NonNullable<
  Awaited<ReturnType<typeof clearWatched>>
>;

export type ClearWatchedMutationError = ErrorType<unknown>;

/**
 * @summary 清空看过记录
 */
export const useClearWatched = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clearWatched>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof clearWatched>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getClearWatchedMutationOptions(options), queryClient);
};
/**
 * 统计当前用户看过电影总数
 * @summary 获取看过总数
 */
export const getWatchedCount = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/watched-movies/count`, method: "GET", signal },
    options,
  );
};

export const getGetWatchedCountQueryKey = () => {
  return ["watched-movies", "count"] as const;
};

export const getGetWatchedCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getWatchedCount>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getWatchedCount>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetWatchedCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchedCount>>> = ({
    signal,
  }) => getWatchedCount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWatchedCount>>,
    TError,
    TData
  >;
};

export type GetWatchedCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWatchedCount>>
>;
export type GetWatchedCountQueryError = ErrorType<unknown>;

/**
 * @summary 获取看过总数
 */

export function useGetWatchedCount<
  TData = Awaited<ReturnType<typeof getWatchedCount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWatchedCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWatchedCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
