/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  BatchIdsDTO,
  GetMyHistoryParams,
  RecordViewHistoryDTO,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 分页获取当前用户的浏览历史记录
 * @summary 获取我的浏览历史
 */
export const getMyHistory = (
  params?: MaybeRef<GetMyHistoryParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/view-histories`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMyHistoryQueryKey = (
  params?: MaybeRef<GetMyHistoryParams>,
) => {
  return ["view-histories", ...(params ? [params] : [])] as const;
};

export const getGetMyHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyHistoryParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyHistory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyHistoryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyHistory>>> = ({
    signal,
  }) => getMyHistory(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyHistory>>,
    TError,
    TData
  >;
};

export type GetMyHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyHistory>>
>;
export type GetMyHistoryQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的浏览历史
 */

export function useGetMyHistory<
  TData = Awaited<ReturnType<typeof getMyHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyHistoryParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyHistory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 显式记录当前用户浏览了某部电影
 * @summary 记录浏览行为
 */
export const recordViewHistory = (
  recordViewHistoryDTO: MaybeRef<RecordViewHistoryDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  recordViewHistoryDTO = unref(recordViewHistoryDTO);

  return customInstance<unknown>(
    {
      url: `/view-histories`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: recordViewHistoryDTO,
      signal,
    },
    options,
  );
};

export const getRecordViewHistoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordViewHistory>>,
    TError,
    { data: BodyType<RecordViewHistoryDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recordViewHistory>>,
  TError,
  { data: BodyType<RecordViewHistoryDTO> },
  TContext
> => {
  const mutationKey = ["recordViewHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recordViewHistory>>,
    { data: BodyType<RecordViewHistoryDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return recordViewHistory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecordViewHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof recordViewHistory>>
>;
export type RecordViewHistoryMutationBody = BodyType<RecordViewHistoryDTO>;
export type RecordViewHistoryMutationError = ErrorType<unknown>;

/**
 * @summary 记录浏览行为
 */
export const useRecordViewHistory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recordViewHistory>>,
      TError,
      { data: BodyType<RecordViewHistoryDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof recordViewHistory>>,
  TError,
  { data: BodyType<RecordViewHistoryDTO> },
  TContext
> => {
  return useMutation(getRecordViewHistoryMutationOptions(options), queryClient);
};
/**
 * 清空当前用户的所有浏览历史
 * @summary 清空浏览历史
 */
export const clearHistory = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/view-histories`, method: "DELETE", signal },
    options,
  );
};

export const getClearHistoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clearHistory>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clearHistory>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["clearHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clearHistory>>,
    void
  > = () => {
    return clearHistory(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof clearHistory>>
>;

export type ClearHistoryMutationError = ErrorType<unknown>;

/**
 * @summary 清空浏览历史
 */
export const useClearHistory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clearHistory>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof clearHistory>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getClearHistoryMutationOptions(options), queryClient);
};
/**
 * 批量删除多条浏览历史记录
 * @summary 批量删除浏览历史
 */
export const deleteHistoryBatch = (
  batchIdsDTO: MaybeRef<BatchIdsDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  batchIdsDTO = unref(batchIdsDTO);

  return customInstance<unknown>(
    {
      url: `/view-histories/batch-delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchIdsDTO,
      signal,
    },
    options,
  );
};

export const getDeleteHistoryBatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteHistoryBatch>>,
    TError,
    { data: BodyType<BatchIdsDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteHistoryBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  const mutationKey = ["deleteHistoryBatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteHistoryBatch>>,
    { data: BodyType<BatchIdsDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return deleteHistoryBatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteHistoryBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteHistoryBatch>>
>;
export type DeleteHistoryBatchMutationBody = BodyType<BatchIdsDTO>;
export type DeleteHistoryBatchMutationError = ErrorType<unknown>;

/**
 * @summary 批量删除浏览历史
 */
export const useDeleteHistoryBatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteHistoryBatch>>,
      TError,
      { data: BodyType<BatchIdsDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteHistoryBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  return useMutation(
    getDeleteHistoryBatchMutationOptions(options),
    queryClient,
  );
};
/**
 * 统计当前用户的浏览历史总数
 * @summary 获取浏览历史总数
 */
export const getHistoryCount = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/view-histories/count`, method: "GET", signal },
    options,
  );
};

export const getGetHistoryCountQueryKey = () => {
  return ["view-histories", "count"] as const;
};

export const getGetHistoryCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getHistoryCount>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHistoryCount>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetHistoryCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistoryCount>>> = ({
    signal,
  }) => getHistoryCount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHistoryCount>>,
    TError,
    TData
  >;
};

export type GetHistoryCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHistoryCount>>
>;
export type GetHistoryCountQueryError = ErrorType<unknown>;

/**
 * @summary 获取浏览历史总数
 */

export function useGetHistoryCount<
  TData = Awaited<ReturnType<typeof getHistoryCount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHistoryCount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHistoryCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 删除指定的浏览历史记录
 * @summary 删除单条浏览历史
 */
export const deleteHistory = (
  historyId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  historyId = unref(historyId);

  return customInstance<unknown>(
    { url: `/view-histories/${historyId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteHistoryMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteHistory>>,
    TError,
    { historyId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteHistory>>,
  TError,
  { historyId: number },
  TContext
> => {
  const mutationKey = ["deleteHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteHistory>>,
    { historyId: number }
  > = (props) => {
    const { historyId } = props ?? {};

    return deleteHistory(historyId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteHistory>>
>;

export type DeleteHistoryMutationError = ErrorType<unknown>;

/**
 * @summary 删除单条浏览历史
 */
export const useDeleteHistory = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteHistory>>,
      TError,
      { historyId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteHistory>>,
  TError,
  { historyId: number },
  TContext
> => {
  return useMutation(getDeleteHistoryMutationOptions(options), queryClient);
};
