/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  BatchIdsDTO,
  GetMyRatingsParams,
  UpdateRatingParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 获取当前登录用户对指定电影的评分；若未评分则返回 null。
 * @summary 获取我的电影评分
 */
export const getUserRating = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/ratings/${movieId}`, method: "GET", signal },
    options,
  );
};

export const getGetUserRatingQueryKey = (movieId: MaybeRef<number>) => {
  return ["ratings", movieId] as const;
};

export const getGetUserRatingQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserRating>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRating>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetUserRatingQueryKey(movieId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRating>>> = ({
    signal,
  }) => getUserRating(movieId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserRating>>,
    TError,
    TData
  >;
};

export type GetUserRatingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserRating>>
>;
export type GetUserRatingQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的电影评分
 */

export function useGetUserRating<
  TData = Awaited<ReturnType<typeof getUserRating>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserRating>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserRatingQueryOptions(movieId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 为指定电影提交评分；若用户已评分则更新原有评分。
 * @summary 提交或更新评分
 */
export const updateRating = (
  movieId: MaybeRef<number>,
  params: MaybeRef<UpdateRatingParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/ratings/${movieId}`,
      method: "PUT",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getUpdateRatingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRating>>,
    TError,
    { movieId: number; params: UpdateRatingParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRating>>,
  TError,
  { movieId: number; params: UpdateRatingParams },
  TContext
> => {
  const mutationKey = ["updateRating"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRating>>,
    { movieId: number; params: UpdateRatingParams }
  > = (props) => {
    const { movieId, params } = props ?? {};

    return updateRating(movieId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRatingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRating>>
>;

export type UpdateRatingMutationError = ErrorType<unknown>;

/**
 * @summary 提交或更新评分
 */
export const useUpdateRating = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRating>>,
      TError,
      { movieId: number; params: UpdateRatingParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateRating>>,
  TError,
  { movieId: number; params: UpdateRatingParams },
  TContext
> => {
  return useMutation(getUpdateRatingMutationOptions(options), queryClient);
};
/**
 * 批量删除当前登录用户的多条评分记录。
 * @summary 批量删除评分
 */
export const deleteRatingsBatch = (
  batchIdsDTO: MaybeRef<BatchIdsDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  batchIdsDTO = unref(batchIdsDTO);

  return customInstance<unknown>(
    {
      url: `/ratings/batch-delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: batchIdsDTO,
      signal,
    },
    options,
  );
};

export const getDeleteRatingsBatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRatingsBatch>>,
    TError,
    { data: BodyType<BatchIdsDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRatingsBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  const mutationKey = ["deleteRatingsBatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRatingsBatch>>,
    { data: BodyType<BatchIdsDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return deleteRatingsBatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRatingsBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRatingsBatch>>
>;
export type DeleteRatingsBatchMutationBody = BodyType<BatchIdsDTO>;
export type DeleteRatingsBatchMutationError = ErrorType<unknown>;

/**
 * @summary 批量删除评分
 */
export const useDeleteRatingsBatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRatingsBatch>>,
      TError,
      { data: BodyType<BatchIdsDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteRatingsBatch>>,
  TError,
  { data: BodyType<BatchIdsDTO> },
  TContext
> => {
  return useMutation(
    getDeleteRatingsBatchMutationOptions(options),
    queryClient,
  );
};
/**
 * 获取当前登录用户对所有已评分电影的评分列表。
 * @summary 获取我的评分列表
 */
export const getMyRatings = (
  params?: MaybeRef<GetMyRatingsParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    { url: `/ratings`, method: "GET", params: unref(params), signal },
    options,
  );
};

export const getGetMyRatingsQueryKey = (
  params?: MaybeRef<GetMyRatingsParams>,
) => {
  return ["ratings", ...(params ? [params] : [])] as const;
};

export const getGetMyRatingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyRatings>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyRatingsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyRatings>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyRatingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyRatings>>> = ({
    signal,
  }) => getMyRatings(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyRatings>>,
    TError,
    TData
  >;
};

export type GetMyRatingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyRatings>>
>;
export type GetMyRatingsQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的评分列表
 */

export function useGetMyRatings<
  TData = Awaited<ReturnType<typeof getMyRatings>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyRatingsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyRatings>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyRatingsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 清空当前登录用户提交的全部评分。
 * @summary 清空我的全部评分
 */
export const clearMyRatings = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/ratings`, method: "DELETE", signal },
    options,
  );
};

export const getClearMyRatingsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clearMyRatings>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clearMyRatings>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["clearMyRatings"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clearMyRatings>>,
    void
  > = () => {
    return clearMyRatings(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearMyRatingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof clearMyRatings>>
>;

export type ClearMyRatingsMutationError = ErrorType<unknown>;

/**
 * @summary 清空我的全部评分
 */
export const useClearMyRatings = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clearMyRatings>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof clearMyRatings>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getClearMyRatingsMutationOptions(options), queryClient);
};
