/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  GetMovieCommentsParams,
  GetMyCommentsParams,
  UpdateCommentContentDTO,
  UpdateCommentWithRatingDTO,
  UpdateLongReviewDTO,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType, BodyType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 修改我在指定电影下的长评。content 字段需为有效的 Tiptap/ProseMirror JSON 文档格式。
 * @summary 修改我的长评
 */
export const updateMyMovieLongReview = (
  movieId: MaybeRef<number>,
  updateLongReviewDTO: MaybeRef<UpdateLongReviewDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  updateLongReviewDTO = unref(updateLongReviewDTO);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/long-reviews/me`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateLongReviewDTO,
      signal,
    },
    options,
  );
};

export const getUpdateMyMovieLongReviewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyMovieLongReview>>,
    TError,
    { movieId: number; data: BodyType<UpdateLongReviewDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyMovieLongReview>>,
  TError,
  { movieId: number; data: BodyType<UpdateLongReviewDTO> },
  TContext
> => {
  const mutationKey = ["updateMyMovieLongReview"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyMovieLongReview>>,
    { movieId: number; data: BodyType<UpdateLongReviewDTO> }
  > = (props) => {
    const { movieId, data } = props ?? {};

    return updateMyMovieLongReview(movieId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyMovieLongReviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyMovieLongReview>>
>;
export type UpdateMyMovieLongReviewMutationBody = BodyType<UpdateLongReviewDTO>;
export type UpdateMyMovieLongReviewMutationError = ErrorType<unknown>;

/**
 * @summary 修改我的长评
 */
export const useUpdateMyMovieLongReview = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMyMovieLongReview>>,
      TError,
      { movieId: number; data: BodyType<UpdateLongReviewDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateMyMovieLongReview>>,
  TError,
  { movieId: number; data: BodyType<UpdateLongReviewDTO> },
  TContext
> => {
  return useMutation(
    getUpdateMyMovieLongReviewMutationOptions(options),
    queryClient,
  );
};
/**
 * 获取当前登录用户对指定电影的评论内容。
 * @summary 获取我的单条评论
 */
export const getMyMovieComment = (
  movieId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);

  return customInstance<unknown>(
    { url: `/movies/${movieId}/comments/me`, method: "GET", signal },
    options,
  );
};

export const getGetMyMovieCommentQueryKey = (movieId: MaybeRef<number>) => {
  return ["movies", movieId, "comments", "me"] as const;
};

export const getGetMyMovieCommentQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyMovieComment>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyMovieComment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyMovieCommentQueryKey(movieId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyMovieComment>>
  > = ({ signal }) => getMyMovieComment(movieId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyMovieComment>>,
    TError,
    TData
  >;
};

export type GetMyMovieCommentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyMovieComment>>
>;
export type GetMyMovieCommentQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的单条评论
 */

export function useGetMyMovieComment<
  TData = Awaited<ReturnType<typeof getMyMovieComment>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyMovieComment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyMovieCommentQueryOptions(movieId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 同时更新我在指定电影下的短评内容和评分分值。
 * @summary 修改我的评论及评分
 */
export const updateMyMovieCommentWithRating = (
  movieId: MaybeRef<number>,
  updateCommentWithRatingDTO: MaybeRef<UpdateCommentWithRatingDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  updateCommentWithRatingDTO = unref(updateCommentWithRatingDTO);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/comments/me`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCommentWithRatingDTO,
      signal,
    },
    options,
  );
};

export const getUpdateMyMovieCommentWithRatingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>,
    TError,
    { movieId: number; data: BodyType<UpdateCommentWithRatingDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentWithRatingDTO> },
  TContext
> => {
  const mutationKey = ["updateMyMovieCommentWithRating"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>,
    { movieId: number; data: BodyType<UpdateCommentWithRatingDTO> }
  > = (props) => {
    const { movieId, data } = props ?? {};

    return updateMyMovieCommentWithRating(movieId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyMovieCommentWithRatingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>
>;
export type UpdateMyMovieCommentWithRatingMutationBody =
  BodyType<UpdateCommentWithRatingDTO>;
export type UpdateMyMovieCommentWithRatingMutationError = ErrorType<unknown>;

/**
 * @summary 修改我的评论及评分
 */
export const useUpdateMyMovieCommentWithRating = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>,
      TError,
      { movieId: number; data: BodyType<UpdateCommentWithRatingDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateMyMovieCommentWithRating>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentWithRatingDTO> },
  TContext
> => {
  return useMutation(
    getUpdateMyMovieCommentWithRatingMutationOptions(options),
    queryClient,
  );
};
/**
 * 只更新我在指定电影下的短评内容，不改变原有评分。
 * @summary 仅修改我的评论内容
 */
export const updateMyMovieCommentContent = (
  movieId: MaybeRef<number>,
  updateCommentContentDTO: MaybeRef<UpdateCommentContentDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  updateCommentContentDTO = unref(updateCommentContentDTO);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/comments/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCommentContentDTO,
      signal,
    },
    options,
  );
};

export const getUpdateMyMovieCommentContentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyMovieCommentContent>>,
    TError,
    { movieId: number; data: BodyType<UpdateCommentContentDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyMovieCommentContent>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentContentDTO> },
  TContext
> => {
  const mutationKey = ["updateMyMovieCommentContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyMovieCommentContent>>,
    { movieId: number; data: BodyType<UpdateCommentContentDTO> }
  > = (props) => {
    const { movieId, data } = props ?? {};

    return updateMyMovieCommentContent(movieId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyMovieCommentContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyMovieCommentContent>>
>;
export type UpdateMyMovieCommentContentMutationBody =
  BodyType<UpdateCommentContentDTO>;
export type UpdateMyMovieCommentContentMutationError = ErrorType<unknown>;

/**
 * @summary 仅修改我的评论内容
 */
export const useUpdateMyMovieCommentContent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMyMovieCommentContent>>,
      TError,
      { movieId: number; data: BodyType<UpdateCommentContentDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateMyMovieCommentContent>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentContentDTO> },
  TContext
> => {
  return useMutation(
    getUpdateMyMovieCommentContentMutationOptions(options),
    queryClient,
  );
};
/**
 * 将评论点赞状态设置为已点赞（幂等）
 * @summary 点赞评论
 */
export const likeComment = (
  commentId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  commentId = unref(commentId);

  return customInstance<unknown>(
    { url: `/comments/${commentId}/like`, method: "PUT", signal },
    options,
  );
};

export const getLikeCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ["likeComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return likeComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeComment>>
>;

export type LikeCommentMutationError = ErrorType<unknown>;

/**
 * @summary 点赞评论
 */
export const useLikeComment = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof likeComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof likeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  return useMutation(getLikeCommentMutationOptions(options), queryClient);
};
/**
 * 将评论点赞状态设置为未点赞（幂等）
 * @summary 取消点赞评论
 */
export const unlikeComment = (
  commentId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  commentId = unref(commentId);

  return customInstance<unknown>(
    { url: `/comments/${commentId}/like`, method: "DELETE", signal },
    options,
  );
};

export const getUnlikeCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unlikeComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unlikeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ["unlikeComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unlikeComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return unlikeComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnlikeCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof unlikeComment>>
>;

export type UnlikeCommentMutationError = ErrorType<unknown>;

/**
 * @summary 取消点赞评论
 */
export const useUnlikeComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unlikeComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof unlikeComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  return useMutation(getUnlikeCommentMutationOptions(options), queryClient);
};
/**
 * 对指定电影发布长评。content 字段需为有效的 Tiptap/ProseMirror JSON 文档格式。
 * @summary 发布长评
 */
export const submitMovieLongReview = (
  movieId: MaybeRef<number>,
  updateLongReviewDTO: MaybeRef<UpdateLongReviewDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  updateLongReviewDTO = unref(updateLongReviewDTO);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/long-reviews`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: updateLongReviewDTO,
      signal,
    },
    options,
  );
};

export const getSubmitMovieLongReviewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitMovieLongReview>>,
    TError,
    { movieId: number; data: BodyType<UpdateLongReviewDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitMovieLongReview>>,
  TError,
  { movieId: number; data: BodyType<UpdateLongReviewDTO> },
  TContext
> => {
  const mutationKey = ["submitMovieLongReview"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitMovieLongReview>>,
    { movieId: number; data: BodyType<UpdateLongReviewDTO> }
  > = (props) => {
    const { movieId, data } = props ?? {};

    return submitMovieLongReview(movieId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitMovieLongReviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitMovieLongReview>>
>;
export type SubmitMovieLongReviewMutationBody = BodyType<UpdateLongReviewDTO>;
export type SubmitMovieLongReviewMutationError = ErrorType<unknown>;

/**
 * @summary 发布长评
 */
export const useSubmitMovieLongReview = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitMovieLongReview>>,
      TError,
      { movieId: number; data: BodyType<UpdateLongReviewDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof submitMovieLongReview>>,
  TError,
  { movieId: number; data: BodyType<UpdateLongReviewDTO> },
  TContext
> => {
  return useMutation(
    getSubmitMovieLongReviewMutationOptions(options),
    queryClient,
  );
};
/**
 * 分页获取指定电影评论。可选按 type 筛选：1-短评，2-长评。可选登录（游客最多查看20条）。
 * @summary 获取电影评论列表
 */
export const getMovieComments = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetMovieCommentsParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/comments`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetMovieCommentsQueryKey = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetMovieCommentsParams>,
) => {
  return ["movies", movieId, "comments", ...(params ? [params] : [])] as const;
};

export const getGetMovieCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMovieComments>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetMovieCommentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMovieCommentsQueryKey(movieId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMovieComments>>
  > = ({ signal }) => getMovieComments(movieId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMovieComments>>,
    TError,
    TData
  >;
};

export type GetMovieCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMovieComments>>
>;
export type GetMovieCommentsQueryError = ErrorType<unknown>;

/**
 * @summary 获取电影评论列表
 */

export function useGetMovieComments<
  TData = Awaited<ReturnType<typeof getMovieComments>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetMovieCommentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMovieComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMovieCommentsQueryOptions(
    movieId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 对指定电影发布短评，每人每部电影仅限一条。
 * @summary 发布短评
 */
export const submitMovieComment = (
  movieId: MaybeRef<number>,
  updateCommentContentDTO: MaybeRef<UpdateCommentContentDTO>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  updateCommentContentDTO = unref(updateCommentContentDTO);

  return customInstance<unknown>(
    {
      url: `/movies/${movieId}/comments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: updateCommentContentDTO,
      signal,
    },
    options,
  );
};

export const getSubmitMovieCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitMovieComment>>,
    TError,
    { movieId: number; data: BodyType<UpdateCommentContentDTO> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitMovieComment>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentContentDTO> },
  TContext
> => {
  const mutationKey = ["submitMovieComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitMovieComment>>,
    { movieId: number; data: BodyType<UpdateCommentContentDTO> }
  > = (props) => {
    const { movieId, data } = props ?? {};

    return submitMovieComment(movieId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitMovieCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitMovieComment>>
>;
export type SubmitMovieCommentMutationBody = BodyType<UpdateCommentContentDTO>;
export type SubmitMovieCommentMutationError = ErrorType<unknown>;

/**
 * @summary 发布短评
 */
export const useSubmitMovieComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitMovieComment>>,
      TError,
      { movieId: number; data: BodyType<UpdateCommentContentDTO> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof submitMovieComment>>,
  TError,
  { movieId: number; data: BodyType<UpdateCommentContentDTO> },
  TContext
> => {
  return useMutation(
    getSubmitMovieCommentMutationOptions(options),
    queryClient,
  );
};
/**
 * 验证长评内容是否为有效的 Tiptap JSON 格式，不保存到数据库。用于前端发布前的校验。
 * @summary 验证 Tiptap JSON 内容
 */
export const validateJsonContent = (
  validateJsonContentBody: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  validateJsonContentBody = unref(validateJsonContentBody);

  return customInstance<unknown>(
    {
      url: `/comments/json/validate`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: validateJsonContentBody,
      signal,
    },
    options,
  );
};

export const getValidateJsonContentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateJsonContent>>,
    TError,
    { data: BodyType<string> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateJsonContent>>,
  TError,
  { data: BodyType<string> },
  TContext
> => {
  const mutationKey = ["validateJsonContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateJsonContent>>,
    { data: BodyType<string> }
  > = (props) => {
    const { data } = props ?? {};

    return validateJsonContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateJsonContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateJsonContent>>
>;
export type ValidateJsonContentMutationBody = BodyType<string>;
export type ValidateJsonContentMutationError = ErrorType<unknown>;

/**
 * @summary 验证 Tiptap JSON 内容
 */
export const useValidateJsonContent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateJsonContent>>,
      TError,
      { data: BodyType<string> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof validateJsonContent>>,
  TError,
  { data: BodyType<string> },
  TContext
> => {
  return useMutation(
    getValidateJsonContentMutationOptions(options),
    queryClient,
  );
};
/**
 * 将 Tiptap JSON 内容解析为纯文本和摘要信息，不保存到数据库。用于前端预览。
 * @summary 解析 Tiptap JSON 内容
 */
export const parseJsonContent = (
  parseJsonContentBody: MaybeRef<string>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  parseJsonContentBody = unref(parseJsonContentBody);

  return customInstance<unknown>(
    {
      url: `/comments/json/parse`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: parseJsonContentBody,
      signal,
    },
    options,
  );
};

export const getParseJsonContentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof parseJsonContent>>,
    TError,
    { data: BodyType<string> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof parseJsonContent>>,
  TError,
  { data: BodyType<string> },
  TContext
> => {
  const mutationKey = ["parseJsonContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof parseJsonContent>>,
    { data: BodyType<string> }
  > = (props) => {
    const { data } = props ?? {};

    return parseJsonContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ParseJsonContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof parseJsonContent>>
>;
export type ParseJsonContentMutationBody = BodyType<string>;
export type ParseJsonContentMutationError = ErrorType<unknown>;

/**
 * @summary 解析 Tiptap JSON 内容
 */
export const useParseJsonContent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof parseJsonContent>>,
      TError,
      { data: BodyType<string> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof parseJsonContent>>,
  TError,
  { data: BodyType<string> },
  TContext
> => {
  return useMutation(getParseJsonContentMutationOptions(options), queryClient);
};
/**
 * 分页获取当前登录用户发布过的所有评论
 * @summary 获取我的评论历史
 */
export const getMyComments = (
  params?: MaybeRef<GetMyCommentsParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/comments/me/history`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetMyCommentsQueryKey = (
  params?: MaybeRef<GetMyCommentsParams>,
) => {
  return ["comments", "me", "history", ...(params ? [params] : [])] as const;
};

export const getGetMyCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyComments>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyCommentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetMyCommentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyComments>>> = ({
    signal,
  }) => getMyComments(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyComments>>,
    TError,
    TData
  >;
};

export type GetMyCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyComments>>
>;
export type GetMyCommentsQueryError = ErrorType<unknown>;

/**
 * @summary 获取我的评论历史
 */

export function useGetMyComments<
  TData = Awaited<ReturnType<typeof getMyComments>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetMyCommentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyCommentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 用户删除自己发布的评论。
 * @summary 删除评论
 */
export const deleteMyComment = (
  commentId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  commentId = unref(commentId);

  return customInstance<unknown>(
    { url: `/comments/${commentId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteMyCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMyComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMyComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ["deleteMyComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMyComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteMyComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMyCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMyComment>>
>;

export type DeleteMyCommentMutationError = ErrorType<unknown>;

/**
 * @summary 删除评论
 */
export const useDeleteMyComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMyComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteMyComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  return useMutation(getDeleteMyCommentMutationOptions(options), queryClient);
};
