/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Movie Review System API
 * Backend API for Movie Review Website
 * OpenAPI spec version: v1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  GetHiddenGemsParams,
  GetPersonalizedMoviesParams,
  GetSimilarMoviesParams,
  GetTrendingMoviesParams,
} from "../../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";
import { customParamsSerializer } from "../../mutator/custom-params-serializer";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 获取今日、本周、本月的热门电影。底层基于 Hive/Spark 计算。
 * @summary 获取趋势榜单
 */
export const getTrendingMovies = (
  params?: MaybeRef<GetTrendingMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/analytics/trending`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetTrendingMoviesQueryKey = (
  params?: MaybeRef<GetTrendingMoviesParams>,
) => {
  return ["analytics", "trending", ...(params ? [params] : [])] as const;
};

export const getGetTrendingMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrendingMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetTrendingMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetTrendingMoviesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTrendingMovies>>
  > = ({ signal }) => getTrendingMovies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrendingMovies>>,
    TError,
    TData
  >;
};

export type GetTrendingMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrendingMovies>>
>;
export type GetTrendingMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 获取趋势榜单
 */

export function useGetTrendingMovies<
  TData = Awaited<ReturnType<typeof getTrendingMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetTrendingMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTrendingMoviesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 读取 stats_user_recs 离线个性化推荐；可选登录，未登录/新用户/无离线结果时自动回退到热门日榜。
 * @summary 猜你喜欢
 */
export const getPersonalizedMovies = (
  params?: MaybeRef<GetPersonalizedMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/analytics/personalized`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetPersonalizedMoviesQueryKey = (
  params?: MaybeRef<GetPersonalizedMoviesParams>,
) => {
  return ["analytics", "personalized", ...(params ? [params] : [])] as const;
};

export const getGetPersonalizedMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonalizedMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonalizedMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalizedMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetPersonalizedMoviesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPersonalizedMovies>>
  > = ({ signal }) => getPersonalizedMovies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonalizedMovies>>,
    TError,
    TData
  >;
};

export type GetPersonalizedMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonalizedMovies>>
>;
export type GetPersonalizedMoviesQueryError = ErrorType<unknown>;

/**
 * @summary 猜你喜欢
 */

export function useGetPersonalizedMovies<
  TData = Awaited<ReturnType<typeof getPersonalizedMovies>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetPersonalizedMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalizedMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonalizedMoviesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 兼容历史路径。建议改用 /movies/{movieId}/similar。
 * @deprecated
 * @summary 相似电影（兼容入口）
 */
export const getSimilarMovies = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  movieId = unref(movieId);
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/analytics/movies/${movieId}/similar`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetSimilarMoviesQueryKey = (
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesParams>,
) => {
  return [
    "analytics",
    "movies",
    movieId,
    "similar",
    ...(params ? [params] : []),
  ] as const;
};

export const getGetSimilarMoviesQueryOptions = <
  TData = Awaited<ReturnType<typeof getSimilarMovies>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimilarMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetSimilarMoviesQueryKey(movieId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSimilarMovies>>
  > = ({ signal }) => getSimilarMovies(movieId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(movieId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSimilarMovies>>,
    TError,
    TData
  >;
};

export type GetSimilarMoviesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSimilarMovies>>
>;
export type GetSimilarMoviesQueryError = ErrorType<unknown>;

/**
 * @deprecated
 * @summary 相似电影（兼容入口）
 */

export function useGetSimilarMovies<
  TData = Awaited<ReturnType<typeof getSimilarMovies>>,
  TError = ErrorType<unknown>,
>(
  movieId: MaybeRef<number>,
  params?: MaybeRef<GetSimilarMoviesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSimilarMovies>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSimilarMoviesQueryOptions(
    movieId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * 直接读取离线分析结果表 stats_hidden_gems，返回最新一期冷门佳作与上榜理由。
 * @summary 获取冷门佳作
 */
export const getHiddenGems = (
  params?: MaybeRef<GetHiddenGemsParams>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customInstance<unknown>(
    {
      url: `/analytics/hidden-gems`,
      method: "GET",
      params: unref(params),
      signal,
    },
    options,
  );
};

export const getGetHiddenGemsQueryKey = (
  params?: MaybeRef<GetHiddenGemsParams>,
) => {
  return ["analytics", "hidden-gems", ...(params ? [params] : [])] as const;
};

export const getGetHiddenGemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getHiddenGems>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetHiddenGemsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHiddenGems>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetHiddenGemsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHiddenGems>>> = ({
    signal,
  }) => getHiddenGems(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHiddenGems>>,
    TError,
    TData
  >;
};

export type GetHiddenGemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHiddenGems>>
>;
export type GetHiddenGemsQueryError = ErrorType<unknown>;

/**
 * @summary 获取冷门佳作
 */

export function useGetHiddenGems<
  TData = Awaited<ReturnType<typeof getHiddenGems>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<GetHiddenGemsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHiddenGems>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHiddenGemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
